/* This file was generated by scramble.py. */
#line 1 "src/all.py"
#ifndef _ALL_
#define _ALL_
typedef struct All All;
#line 1
#include "common.h"
#line 3
struct All {
    int FPS;
    int w, h;
    LandFont * font;
    LandFont * medium;
    LandFont * big;
#line 11
    bool up, down, left, right, jump;
#line 13
    int ftpos;
    double frame_times [60];
    float direct_speed_measure;
#line 17
    bool show_fps;
    bool show_help;
#line 20
    int cheatpos [10];
#line 22
    LandColor text;
#line 24
    bool title;
#line 26
    bool editor_enabled;
    bool editor;
    int text_input;
    int cursor;
#line 31
    LandColor tint;
#line 39
    int dpad;
    int music;
    int sound;
#line 43
    int load_after_redraw;
    bool find_entrance;
#line 46
    int time;
    bool overview;
    bool render_screenshot;
#line 50
    int code;
    bool godmode;
#line 53
    bool swipe;
    double swipex, swipey, swipet, swipej;
#line 56
    int resize_in_ticks;
    bool show_map;
    bool show_ad;
#line 60
    bool test;
};
#endif
/* This file was generated by scramble.py. */
