/* This file was generated by scramble.py. */
#line 1 "src/barrel.py"
#ifndef _BARREL_
#define _BARREL_
#line 1
#include "cube.h"
#line 3
void barrel_touch(Block * super, Block * c, float x, float y, float z);
#endif
/* This file was generated by scramble.py. */
