/* This file was generated by scramble.py. */
#line 1 "src/barrel.py"
#include "barrel.h"
#line 3
void barrel_touch(Block * super, Block * c, float x, float y, float z) {
    cube_touch(super, c, x, y, z);
    if (y < 0) {
        if (c->block_type == Render_RampLeft) {
            super->frame = 1;
        }
#line 8
        else if (c->block_type == Render_RampRight) {
            super->frame = 2;
        }
#line 9
        else {
#line 11
            super->frame = 0;
        }
    }
}
/* This file was generated by scramble.py. */
