/* This file was generated by scramble.py. */
#line 1 "src/block_type.py"
#include "block_type.h"
#include "render.h"
static void fill_in(void);
#line 24
LandArray * block_types;
#line 31
BlockType* blocktype_new(char const * name, float xs, float ys, float zs, void(* tick)(Block *), void(* touch)(Block *, Block *, float, float, float), void(* destroy)(Block *), Block * (* allocate)(void), void(* post_init)(Block *)) {
    BlockType * self;
    land_alloc(self);
    self->name = land_strdup(name);
    self->xs = xs;
    self->ys = ys;
    self->zs = zs;
    self->dynamic = 0;
    self->lift = 0;
    self->transparent = 0;
    self->tick = tick;
    self->touch = touch;
    self->destroy = destroy;
    self->allocate = allocate;
    self->post_init = post_init;
    return self;
}
void blocktype_destroy(BlockType * self) {
    if (self->bitmaps) {
        {
#line 50
            LandArrayIterator __iter0__ = LandArrayIterator_first(self->bitmaps);
#line 50
            for (LandImage * pic = LandArrayIterator_item(self->bitmaps, &__iter0__); LandArrayIterator_next(self->bitmaps, &__iter0__); pic = LandArrayIterator_item(self->bitmaps, &__iter0__)) {
                land_image_destroy(pic);
            }
        }
#line 52
        land_array_destroy(self->bitmaps);
    }
#line 53
    land_free(self);
}
bool blocktype_preload(BlockType * self) {
    {
#line 56
        LandArrayIterator __iter0__ = LandArrayIterator_first(self->bitmaps);
#line 56
        for (LandImage * pic = LandArrayIterator_item(self->bitmaps, &__iter0__); LandArrayIterator_next(self->bitmaps, &__iter0__); pic = LandArrayIterator_item(self->bitmaps, &__iter0__)) {
            if (land_image_load_on_demand(pic)) {
                return 1;
            }
        }
    }
#line 59
    return 0;
}
static BlockType * block_types_flowers [8];
static void fill_in(void) {
    block_types_flowers [1] = Render_Gentian;
    block_types_flowers [2] = Render_Edelweiss;
    block_types_flowers [3] = Render_Orchid;
    block_types_flowers [4] = Render_Hyacinth;
    block_types_flowers [5] = Render_Sunflower;
    block_types_flowers [6] = Render_Rose;
    block_types_flowers [7] = Render_Belladonna;
}
int block_type_flower(BlockType * self) {
    fill_in();
    for (int i = 1; i < 8; i += 1) {
        if (self == block_types_flowers [i]) {
            return i;
        }
    }
#line 76
    return 0;
}
BlockType* block_flower(int i) {
    fill_in();
    return block_types_flowers [i];
}
/* This file was generated by scramble.py. */
