/* This file was generated by scramble.py. */
#line 1 "src/cart.py"
#ifndef _CART_
#define _CART_
#line 1
#include "block.h"
#include "game.h"
#line 4
void cart_tick(Block * super);
#endif
/* This file was generated by scramble.py. */
