/* This file was generated by scramble.py. */
#line 1 "src/common.py"
#include "common.h"
#line 5
void print(char const * str, ...) {
    va_list args;
    va_start(args, str);
    vprintf(str, args);
    va_end(args);
    printf("\n");
}
#line 14
static All a;
All * global_a = & a;
/* This file was generated by scramble.py. */
