/* This file was generated by scramble.py. */
#line 1 "src/common.py"
#ifndef _COMMON_
#define _COMMON_
#line 1
#include "land/land.h"
#include "all.h"
#line 5
void print(char const * str, ...);
#line 12
#define pi LAND_PI
#line 15
extern All * global_a;
#endif
/* This file was generated by scramble.py. */
