/* This file was generated by scramble.py. */
#line 1 "src/common.py"
#ifndef _COMMON_
#define _COMMON_
#line 1
#include "land/land.h"
#include "all.h"
#line 4
void print(char const * s, ...);
#line 11
#define pi LAND_PI
#line 14
extern All * global_a;
#endif
/* This file was generated by scramble.py. */
