/* This file was generated by scramble.py. */
#line 1 "src/config.py"
#include "config.h"
#line 3
char const * VERSION = "1.23";
bool global_can_enable_editor = 0;
bool global_use_touch_input = 0;
#line 29
Controls controls;
#line 31
void config_controls_read(void) {
    controls.c [ControlLeft] [0] = LandKeyLeft;
    controls.c [ControlLeft] [1] = 'a';
    controls.c [ControlRight] [0] = LandKeyRight;
    controls.c [ControlRight] [1] = 'd';
    controls.c [ControlUp] [0] = LandKeyUp;
    controls.c [ControlUp] [1] = 'w';
    controls.c [ControlDown] [0] = LandKeyDown;
    controls.c [ControlDown] [1] = 's';
    controls.c [ControlJump] [0] = LandKeyLeftControl;
    controls.c [ControlJump] [1] = LandKeyRightControl;
    controls.c [ControlJump] [2] = LandKeyEnter;
    controls.c [ControlMenu] [0] = LandKeyBackspace;
}
void config_check_controls(All * a) {
    for (int j = 0; j < ControlCount; j += 1) {
        controls.pressed [j] = ! controls.down [j];
        controls.down [j] = 0;
        for (int i = 0; i < 3; i += 1) {
            if (land_key(controls.c [j] [i])) {
#line 50
                controls.down [j] = 1;
            }
        }
#line 51
        float threshold = controls.axis [j] [1] / 100.0;
        if (land_joystick_axis(controls.axis [j] [0]) * threshold > threshold * threshold) {
            controls.down [j] = 1;
        }
#line 54
        if (land_joystick_button(controls.button [j])) {
            controls.down [j] = 1;
        }
#line 56
        if (! controls.down [j]) {
            controls.pressed [j] = 0;
        }
    }
#line 58
    a->left = controls.down [ControlLeft];
    a->right = controls.down [ControlRight];
    a->up = controls.down [ControlUp];
    a->down = controls.down [ControlDown];
    a->jump = controls.down [ControlJump];
}
int config_joystick_control(int control, int progress) {
    if (progress == 0) {
        controls.axis [control] [0] = 0;
        controls.axis [control] [1] = 0;
        controls.button [control] = 0;
    }
    int an = land_joystick_axis_count();
    for (int ai = 1; ai < an; ai += 1) {
        float a = land_joystick_axis(ai);
        float d = land_joystick_delta_axis(ai);
        if (fabs(a) > 0.2 && (fabs(d) > 0 || ai == controls.axis [control] [0])) {
            if (fabs(a * 25) > fabs(controls.axis [control] [1])) {
                controls.axis [control] [0] = ai;
                controls.axis [control] [1] = a * 25;
            }
#line 78
            return FoundAxis;
        }
    }
#line 79
    int bn = land_joystick_button_count();
    for (int bi = 1; bi < bn; bi += 1) {
        if (land_joystick_button_pressed(bi)) {
            controls.button [control] = bi;
            // initialize state for the new control
            controls.down [control] = 1;
            controls.pressed [control] = 0;
            return FoundButton;
        }
    }
#line 87
    return FoundNothing;
}
void config_print_controls(LandFile * f) {
    for (int j = 0; j < ControlCount; j += 1) {
#line 92
        land_file_print(f, "control %d 0 %d %d", j, controls.axis [j] [0], controls.axis [j] [1]);
#line 94
        land_file_print(f, "control %d 1 %d 0", j, controls.button [j]);
    }
}
#line 96
void config_read_controls(str row) {
    if (land_starts_with(row, "control ")) {
        int a, b, c, d;
        sscanf(row, "control %d %d %d %d", & a, & b, & c, & d);
        if (b == 0) {
            controls.axis [a] [0] = c;
            controls.axis [a] [1] = d;
        }
#line 103
        else if (b == 1) {
            controls.button [a] = c;
        }
    }
}
#line 106
str control_name(int c) {
    if (controls.button [c]) {
#line 107
        return land_joystick_button_name(controls.button [c]);
    }
#line 108
    if (controls.axis [c] [0]) {
#line 108
        return land_joystick_axis_name(controls.axis [c] [0]);
    }
#line 109
    return "none";
}
/* This file was generated by scramble.py. */
