/* This file was generated by scramble.py. */
#line 1 "src/config.py"
#ifndef _CONFIG_
#define _CONFIG_
typedef struct Controls Controls;
#line 1
#include "common.h"
#line 3
extern char const * VERSION;
extern bool global_can_enable_editor;
#line 6
enum {
    ControlLeft,
    ControlRight,
    ControlUp,
    ControlDown,
    ControlJump,
    ControlCount
};
struct Controls {
    int c [ControlCount] [3];
    bool down [ControlCount];
};
#line 19
void config_controls_read(void);
#line 31
void config_check_controls(All * a);
#endif
/* This file was generated by scramble.py. */
