/* This file was generated by scramble.py. */
#line 1 "src/config.py"
#ifndef _CONFIG_
#define _CONFIG_
typedef struct Controls Controls;
#line 1
#include "common.h"
#line 3
extern char const * VERSION;
extern bool global_can_enable_editor;
extern bool global_use_touch_input;
#line 7
enum {
    FoundNothing,
    FoundButton,
    FoundAxis
};
enum {
    ControlNone,
    ControlLeft,
    ControlRight,
    ControlUp,
    ControlDown,
    ControlJump,
    ControlMenu,
    ControlUnused,
    ControlCount
};
struct Controls {
    int c [ControlCount] [3];
    int down [ControlCount];
    int pressed [ControlCount];
    int axis [ControlCount] [2] /* number, inverted */;
    int button [ControlCount];
};
#line 29
extern Controls controls;
#line 31
void config_controls_read(void);
#line 45
void config_check_controls(All * a);
#line 64
int config_joystick_control(int control, int progress);
#line 89
void config_print_controls(LandFile * f);
#line 96
void config_read_controls(str row);
#line 106
str control_name(int c);
#endif
/* This file was generated by scramble.py. */
