/* This file was generated by scramble.py. */
#line 1 "src/config.py"
#ifndef _CONFIG_
#define _CONFIG_
typedef struct Controls Controls;
#line 1
#include "common.h"
#line 3
extern char const * VERSION;
extern bool global_can_enable_editor;
extern bool global_use_touch_input;
#line 7
enum {
    FoundNothing,
    FoundButton,
    FoundAxis
};
enum {
    ControlNone,
    ControlLeft,
    ControlRight,
    ControlUp,
    ControlDown,
    ControlJump,
    ControlMenu,
    ControlUnused,
    ControlCount
};
struct Controls {
    int c [ControlCount] [3] /* key alt-key alt-key-2 */;
    int down [ControlCount];
    float strength [ControlCount];
    int pressed [ControlCount];
    int axis [ControlCount] [3] /* number, threshold (+/-) */;
    float detection [LandJoystickAxesCount];
    float zero [LandJoystickAxesCount];
    int button [ControlCount];
};
#line 32
extern Controls controls;
#line 34
void config_controls_read(void);
#line 75
void config_check_controls(All * a);
#line 103
int config_joystick_control(int control, int progress);
#line 135
void config_print_controls(LandFile * f);
#line 142
void config_read_controls(str row);
#line 152
str control_name(int c);
#endif
/* This file was generated by scramble.py. */
