/* This file was generated by scramble.py. */
#line 1 "src/cube.py"
#include "cube.h"
#line 7
Cube* cube_new(Blocks * blocks, float x, float y, float z, BlockType * kind) {
    Cube * self;
    land_alloc(self);
    block_init((void *) self, blocks, x, y, z, kind);
    return self;
}
void cube_touch(Block * super, Block * c, float dx, float dy, float dz) {
    if (dy < 0 && c->block_type == Render_Plate) {
        float x1 = c->x + c->xs / 3;
        float z1 = c->z + c->zs / 3;
        float x2 = c->x + c->xs - c->xs / 3;
        float z2 = c->z + c->zs - c->zs / 3;
#line 20
        if (super->x < x2 && super->z < z2 && super->x + super->xs > x1 && super->z + super->zs > z1) {
            c->frame = 1;
        }
    }
}
/* This file was generated by scramble.py. */
