/* This file was generated by scramble.py. */
#line 1 "src/cube.py"
#ifndef _CUBE_
#define _CUBE_
typedef struct Cube Cube;
#line 1
#include "common.h"
#include "block.h"
#line 2
#include "render.h"
#line 4
struct Cube {
    Block super;
};
Cube* cube_new(Blocks * blocks, float x, float y, float z, BlockType * kind);
#line 13
void cube_touch(Block * super, Block * c, float dx, float dy, float dz);
#endif
/* This file was generated by scramble.py. */
