/* This file was generated by scramble.py. */
#line 1 "src/debug.py"
#ifndef _DEBUG_
#define _DEBUG_
#line 1
#include "common.h"
#line 3
extern bool debug_no_mask;
extern int debug_bounding_boxes;
#endif
/* This file was generated by scramble.py. */
