/* This file was generated by scramble.py. */
#line 1 "src/editor.py"
#include "editor.h"
#line 10
Editor * editor;
#line 12
void editor_new(void) {
    land_alloc(editor);
}
void editor_del(void) {
    land_free(editor);
    editor = NULL;
}
bool editor_click(LandFloat mx, LandFloat my, bool clicked, bool released) {
#line 21
    if (clicked) {
        Block * p = blocks_pick(game->blocks, mx, my, game->viewport);
        if (! p) {
            editor->picked = NULL;
            return 0;
        }
#line 26
        editor->mx = mx;
        editor->my = my;
        editor->ox = p->x;
        editor->oy = p->y;
        editor->oz = p->z;
        editor->picked = p;
        return 1;
    }
#line 32
    else {
#line 34
        if (editor->picked) {
#line 36
            LandFloat dx = mx - editor->mx;
            LandFloat dy = my - editor->my;
#line 39
            dx /= game->viewport->zoom;
            dy /= game->viewport->zoom;
#line 42
            float ang = (atan2(dy * 2, dx) + pi) * 8 / 2 / pi;
            float r = sqrt(dx * dx + dy * dy);
            if (r < 12) {
                return 1;
            }
            dx += dx * (- 12 / r);
            dy += dy * (- 12 / r);
#line 50
            Block * p = editor->picked;
#line 52
            p->x = editor->ox;
            p->y = editor->oy;
            p->z = editor->oz;
#line 56
            float s = 24;
            //       2
            //    1     3
            //  0    *    4
            //    7     5
            //       6
            if (fabs(ang - 2) < 0.5 || fabs(ang - 6) < 0.5) {
                float ox, oy, y;
                project(game->viewport, p->x, p->y, p->z, & ox, & oy);
                unproject_y(game->viewport, oy + dy, p->x, p->z, & y);
#line 67
                p->y = floor(y / s + 0.1) * s;
            }
#line 68
            else if (ang < 0.5 || ang > 7.5 || fabs(ang - 4) < 0.5) {
#line 68
                ;
            }
#line 68
            else {
#line 71
                float ox, oy, x, z;
                project(game->viewport, p->x, p->y, p->z, & ox, & oy);
                unproject(game->viewport, ox + dx, oy + dy, p->y, & x, & z);
#line 75
                if (fabs(x - p->x) > fabs(z - p->z)) {
                    p->x = floor(x / s + 0.1) * s;
                }
#line 76
                else {
#line 78
                    p->z = floor(z / s + 0.1) * s;
                }
            }
#line 79
            game_recalc();
#line 81
            return 1;
        }
    }
#line 82
    if (released) {
        return 1;
    }
#line 84
    return 0;
}
/* This file was generated by scramble.py. */
