/* This file was generated by scramble.py. */
#line 1 "src/editor.py"
#ifndef _EDITOR_
#define _EDITOR_
typedef struct Editor Editor;
#line 1
#include "common.h"
#include "block.h"
#include "game.h"
#line 7
struct Editor {
    LandFloat mx, my;
    float ox, oy, oz;
    Block * picked;
};
extern Editor * editor;
#line 14
void editor_new(void);
#line 17
void editor_del(void);
#line 21
bool editor_click(LandFloat mx, LandFloat my, bool clicked, bool released);
#endif
/* This file was generated by scramble.py. */
