/* This file was generated by scramble.py. */
#line 1 "src/event.py"
#include "event.h"
#line 2
#ifdef ANDROID
#include "allegro5/allegro_android.h"
#line 3
#endif
#line 6
void event(char const * format, ...) {
    LandBuffer * b = land_buffer_new();
    va_list args;
    va_start(args, format);
    land_buffer_addv(b, format, args);
    va_end(args);
    char * data = land_buffer_finish(b);
    #ifdef ANDROID
    JNIEnv * env = al_android_get_jni_env();
#line 16
    jclass class_id = (* env)->GetObjectClass(env, al_android_get_activity());
    jmethodID method_id = (* env)->GetMethodID(env, class_id, "postEvent", "(Ljava/lang/String;)V");
#line 19
    jstring jdata = (* env)->NewStringUTF(env, data);
    (* env)->CallVoidMethod(env, al_android_get_activity(), method_id, jdata);
    (* env)->DeleteLocalRef(env, jdata);
    land_log_message("%s", data);
#line 22
    #endif
#line 24
    land_free(data);
}
/* This file was generated by scramble.py. */
