/* This file was generated by scramble.py. */
#line 1 "src/event.py"
#ifndef _EVENT_
#define _EVENT_
#line 1
#include "common.h"
#line 6
void event(char const * format, ...);
#line 27
void show_interstitial_ad(void);
#line 36
bool show_ad_done(void);
#line 47
void open_link(str url);
#endif
/* This file was generated by scramble.py. */
