/* This file was generated by scramble.py. */
#line 1 "src/event.py"
#ifndef _EVENT_
#define _EVENT_
#line 1
#include "common.h"
#line 6
void event(char const * format, ...);
#endif
/* This file was generated by scramble.py. */
