/* This file was generated by scramble.py. */
#line 1 "src/eye.py"
#ifndef _EYE_
#define _EYE_
#line 1
#include "common.h"
#include "block.h"
#line 2
#include "render.h"
#line 4
void eye_tick(Block * super);
#endif
/* This file was generated by scramble.py. */
