/* This file was generated by scramble.py. */
#line 1 "src/gremlin.py"
#ifndef _GREMLIN_
#define _GREMLIN_
typedef struct Gremlin Gremlin;
#line 1
#include "block.h"
#include "game.h"
#line 4
struct Gremlin {
    Block super;
    int respect;
};
Block* gremlin_allocate(void);
#line 14
void gremlin_tick(Block * super);
#line 40
void gremlin_touch(Block * super, Block * c, float dx, float dy, float dz);
#endif
/* This file was generated by scramble.py. */
