/* This file was generated by scramble.py. */
#line 1 "src/input.py"
#ifndef _INPUT_
#define _INPUT_
#line 1
#include "common.h"
#include "main.h"
#include "menu.h"
#include "editor.h"
#line 35
void input_toggle_pause(void);
#line 45
void input_tick(void);
#endif
/* This file was generated by scramble.py. */
