/* This file was generated by scramble.py. */
#line 1 "src/input.py"
#ifndef _INPUT_
#define _INPUT_
#line 1
#include "common.h"
#include "main.h"
#include "menu.h"
#include "editor.h"
#line 38
void input_tick(void);
#endif
/* This file was generated by scramble.py. */
