/* This file was generated by scramble.py. */
#line 1 "src/intro.py"
#include "intro.h"
typedef struct Smoke Smoke;
static void find_test_tube(void);
static void walls_down(bool final);
static void move_car(void);
static void extro(void);
static void set_back_color(float r, float g, float b);
static void fade_back_color(float r, float g, float b);
static void set_tint_color(float r, float g, float b);
static void fade_tint_color(float r, float g, float b);
static void intro(void);
static void setup_smoke(void);
static void postprocess1(void);
static void postprocess2(void);
#line 3
LandColor intro_tint;
LandColor intro_back;
static Block * test_tube;
static int ty;
static int scrolly;
#line 9
static void find_test_tube(void) {
    if (test_tube) {
#line 10
        return ;
    }
    {
#line 12
        LandArrayIterator __iter0__ = LandArrayIterator_first(game->blocks->dynamic);
#line 12
        for (Block * b = LandArrayIterator_item(game->blocks->dynamic, &__iter0__); LandArrayIterator_next(game->blocks->dynamic, &__iter0__); b = LandArrayIterator_item(game->blocks->dynamic, &__iter0__)) {
            if (b->block_type == Render_TestTube) {
                if (b->frame == 5) {
                    if (b->x < 0 && b->y > 0) {
                        test_tube = b;
#line 16
                        return ;
                    }
                }
            }
        }
    }
}
#line 19
#define SN 100
#define STARN 500
struct Smoke {
    bool active;
    float x, y, z;
    float sx, sy;
    float dx, dy, dz;
    float ax, ay, az;
    float r, g, b, a;
    bool two;
#line 28
};
static Smoke smokes [STARN];
static bool smoke;
#line 32
static void walls_down(bool final) {
    {
#line 33
        LandArrayIterator __iter0__ = LandArrayIterator_first(game->blocks->fixed);
#line 33
        for (Block * b = LandArrayIterator_item(game->blocks->fixed, &__iter0__); LandArrayIterator_next(game->blocks->fixed, &__iter0__); b = LandArrayIterator_item(game->blocks->fixed, &__iter0__)) {
            if (b->block_type == Render_WallLeft || b->block_type == Render_WallRight) {
                b->y -= land_rand(8, 12);
                if (final) {
                    b->y = - 9000;
                }
#line 38
                game->blocks->rebuild_static_cache = 1;
            }
        }
    }
}
#line 40
static void move_car(void) {
    {
#line 41
        LandArrayIterator __iter0__ = LandArrayIterator_first(game->blocks->fixed);
#line 41
        for (Block * b = LandArrayIterator_item(game->blocks->fixed, &__iter0__); LandArrayIterator_next(game->blocks->fixed, &__iter0__); b = LandArrayIterator_item(game->blocks->fixed, &__iter0__)) {
            if (b->block_type == Render_Car) {
                b->dz += 0.1;
                b->z += b->dz;
                b->frame = 1;
                game->blocks->rebuild_static_cache = 1;
            }
        }
    }
}
#line 48
void intro_sequence(void) {
    if (game->sequence == 1) {
        intro();
    }
#line 51
    if (game->sequence == 2) {
        extro();
    }
}
#line 54
static void extro(void) {
    Game * g = game;
    int t = g->sequence_ticks++;
    set_back_color(0, 0, 0);
    game->player->super.y = 9000;
    if (t < 60 * 5) {
        move_car();
        set_tint_color(1, 1, 1);
        smokes [0].active = 0;
    }
#line 62
    else {
#line 64
        fade_tint_color(0, 0, 0);
        scrolly++;
#line 67
        if (! smokes [0].active) {
            for (int i = 0; i < STARN; i += 1) {
                Smoke * s = smokes + i;
                s->active = 1;
                s->x = land_rnd(- 480, 480);
                s->y = land_rnd(- 480, 480);
                s->z = land_rnd(- 480, 480);
                s->two = land_rnd(0, 100) < 2;
            }
        }
#line 74
        else {
#line 76
            for (int i = 0; i < STARN; i += 1) {
                Smoke * s = smokes + i;
                s->z += 1;
                if (s->z > 480) {
                    s->z -= 960;
                }
            }
        }
    }
}
#define set__color(X, r, g, b) \
    LandColor * c = & intro_ ##X; \
    c->r = r; \
    c->g = g; \
    c->b = b; \
    c->a = 1;
#define fade__color(X, r, g, b, p) \
    double q = 1 - p; \
    LandColor * c = & intro_ ##X; \
    c->r *= p; \
    c->r += q * r; \
    c->g *= p; \
    c->g += q * g; \
    c->b *= p; \
    c->b += q * b; \
    c->a = 1;
#line 100
static void set_back_color(float r, float g, float b) {
    set__color(back, r, g, b);
}
static void fade_back_color(float r, float g, float b) {
    fade__color(back, r, g, b, 0.95);
}
static void set_tint_color(float r, float g, float b) {
    set__color(tint, r, g, b);
}
static void fade_tint_color(float r, float g, float b) {
    fade__color(tint, r, g, b, 0.99);
}
static void intro(void) {
    All * a = global_a;
    Game * g = game;
#line 116
    a->right = 0;
    a->left = 0;
    a->down = 0;
    a->up = 0;
    a->jump = 0;
    int t = g->sequence_ticks++;
    if (t == 1) {
        smoke = 0;
        set_back_color(0, 0, 0);
        set_tint_color(1, 1, 1);
        test_tube = NULL;
        find_test_tube();
        if (! test_tube) {
            g->sequence = 0;
#line 129
            return ;
        }
    }
#line 131
    int w = 60 * 2.5;
    if (t < w) {
        a->left = 1;
        a->up = 1;
        fade_tint_color(.8, .8, .8);
    }
#line 136
    else if (t < w + 60 * 0.5) {
        a->jump = 1;
        ty = test_tube->y;
    }
#line 139
    else if (t < w + 60 * 1) {
        a->jump = 1;
        a->right = 1;
        a->down = 1;
        test_tube->x = g->player->super.x - 72;
        test_tube->z = g->player->super.z;
        test_tube->y = ty;
    }
#line 146
    else if (t < w + 60 * 5) {
        if (test_tube->y < - 8000) {
            if (! smoke) {
                setup_smoke();
            }
        }
#line 150
        if (t > w + 60 * 4) {
            fade_tint_color(1, 0.8, 0.1);
        }
    }
#line 152
    else if (t < w + 60 * 6) {
        fade_tint_color(1, 1, 1);
        walls_down(0);
    }
#line 155
    else if (t < w + 60 * 7) {
        fade_tint_color(1, 1, 1);
        fade_back_color(1, 1, 1);
        walls_down(0);
    }
#line 158
    else {
#line 160
        walls_down(1);
        strcpy(g->title, "What happened to the walls?");
        g->sequence = 0;
    }
}
#line 164
void intro_postprocess(void) {
    if (game->sequence == 1) {
        postprocess1();
    }
#line 167
    if (game->sequence == 2) {
        postprocess2();
    }
}
#line 170
static void setup_smoke(void) {
    if (smoke) {
#line 171
        return ;
    }
    smoke = 1;
    for (int i = 0; i < SN; i += 1) {
        Smoke * s = smokes + i;
        s->active = 1;
        s->x = game->player->super.x - 72;
        s->z = game->player->super.z;
        s->y = 0;
        s->sx = 0.1;
        s->sy = 0.1;
        float r = land_rnd(0, 2 * pi);
        s->ax = cos(r) * 0.015;
        s->az = sin(r) * 0.015;
        s->ay = - 0.2;
        s->dx = s->ax * land_rnd(- 60, 60);
        s->dy = land_rnd(1, 5);
        s->dz = s->az * land_rnd(- 60, 60);
        s->a = 0.3;
        s->r = land_rnd(0.8, 1);
        s->g = land_rnd(0.5, 1);
        s->b = land_rnd(0, 0.4);
    }
}
#line 194
static void postprocess1(void) {
    if (smoke) {
        for (int i = 0; i < SN; i += 1) {
            Smoke * s = smokes + i;
            float a = s->a;
            float r = s->r * a;
            float g = s->g * a;
            float b = s->b * a;
            float sx, sy;
            project(game->viewport, s->x, s->y, s->z, & sx, & sy);
#line 206
            land_image_draw_scaled_tinted(Render_Smoke, sx, sy, s->sx, s->sy, r, g, b, a);
            s->x += s->dx;
            s->y += s->dy;
            if (s->y < 0) {
                s->y = 0;
                s->dy = - s->dy;
            }
#line 212
            s->z += s->dz;
            s->sx += 0.01;
            s->sy += 0.01;
            s->dx += s->ax;
            s->dy += s->ay;
            s->dz += s->az;
            s->a *= 0.99;
        }
    }
}
#line 220
static char const credits [] = "\n"
    "Yellow and Dangerous\n"
    "\n"
    "\n"
    "by\n"
    "\n"
    "^Allefant\n"
    "\n"
    "\n"
    "Thanks for playing!\n"
    "\n"
    "Hope you enjoyed it!\n"
    "\n"
    "\n"
    "^Programming\n"
    "\n"
    "Elias Pschernig\n"
    "\n"
    "^Graphics\n"
    "\n"
    "Elias Pschernig\n"
    "\n"
    "^Level Design\n"
    "\n"
    "Elias Pschernig\n"
    "\n"
    "^Music\n"
    "\n"
    "\"Manic Polka\" Kevin MacLeod (incompetech.com)\n"
    "\"Pixel Peeker Polka - slower\" Kevin MacLeod (incompetech.com)\n"
    "\"Overcast\" Kevin MacLeod (incompetech.com)\n"
    "\"Allefant Song\" Elias Pschernig\n"
    "\"Katjusha\"\n"
    "\"Dance of the Sugar Plum Fairy\"\n"
    "\n"
    "^Publishing\n"
    "\n"
    "Rachel Morris\n"
    "\n"
    "\n"
    "\n"
    "^Thanks to\n"
    "\n"
    "\n"
    "Andrea Avers\n"
    "_<3\n"
    "\n"
    "Thomas Fjellstrom\n"
    "_android port Allegro\n"
    "\n"
    "Trent Gamblin\n"
    "_Allegro library, inspiration\n"
    "\n"
    "Pavel Sountsov\n"
    "_Allegro library\n"
    "\n"
    "Peter Wang\n"
    "_Allegro library\n"
    "\n"
    "Peter Hull\n"
    "_OSX port Allegro\n"
    "\n"
    "Shawn Hargreaves\n"
    "_Allegro library\n"
    "\n"
    "Eric Botcazou\n"
    "_Allegro library\n"
    "\n"
    "Jon Rafkind\n"
    "_Allegro library\n"
    "\n"
    "Milan Mimica\n"
    "_Allegro library\n"
    "\n"
    "Beoran\n"
    "_Allegro library\n"
    "\n"
    "Matthew Leverton\n"
    "allegro.cc\n"
    "\n"
    "Evert Gleebbeek\n"
    "_Allegro library\n"
    "\n"
    "Grzegorz Adam Hankiewicz\n"
    "_Allegro library\n"
    "\n"
    "Angelo Mottola\n"
    "_Allegro library\n"
    "\n"
    "Jonathan Seeley\n"
    "_distracting me on IRC\n"
    "\n"
    "\n"
    "\n"
    "Made with\n"
    "\n"
    "\n"
    "\n"
    "^Allegro\n"
    "Game Programming Library\n"
    "\n"
    "^Blender\n"
    "3D Modeler\n"
    "\n"
    "^Gimp\n"
    "Image Manipulator\n"
    "\n"
    "^Geany\n"
    "Code Editor\n"
    "\n"
    "^Scramble\n"
    "Pythonic C Compiler\n"
    "";
#line 333
static LandArray * rows;
static void postprocess2(void) {
    int t = game->sequence_ticks;
    All * a = global_a;
    float w = land_display_width();
    float h = land_display_height();
#line 340
    Viewport * v = game->viewport;
    if (smokes [0].active) {
        // frames used in the title so always loaded
        LandImage * pic = land_array_get_nth(Render_Gremlin->bitmaps, 0);
        LandImage * pic2 = land_array_get_nth(Render_Allefant->bitmaps, 8);
        for (int i = 0; i < STARN; i += 1) {
            Smoke * s = smokes + i;
            float pz = 480 - s->z;
            float z = 16 / pz;
            float angle = t * pi / 300;
            float rx = s->x * cos(angle) + s->y * sin(angle);
            float ry = s->y * cos(angle) - s->x * sin(angle);
            float px = w / 2 / v->zoom + rx * z * 16;
            float py = h / 2 / v->zoom + ry * z * 4;
            px = px - 256 * z;
            py = py - 256 * z;
            land_image_draw_scaled(s->two ? pic2 : pic, px, py, z, z);
        }
    }
#line 358
    if (! rows) {
        rows = land_text_splitlines(credits);
    }
    land_color(1, 1, 1, 1);
    land_text_pos(480, 480 - scrolly);
    {
#line 363
        LandArrayIterator __iter0__ = LandArrayIterator_first(rows);
#line 363
        for (char * row = LandArrayIterator_item(rows, &__iter0__); LandArrayIterator_next(rows, &__iter0__); row = LandArrayIterator_item(rows, &__iter0__)) {
            if (row [0] == '_') {
                land_font_set(a->font);
                row++;
            }
#line 367
            else if (row [0] == '^') {
                land_font_set(a->big);
                row++;
            }
#line 369
            else {
#line 372
                land_font_set(a->medium);
            }
#line 373
            land_print_center(row);
        }
    }
#line 375
    if (land_text_y_pos() < 0) {
        scrolly = 0;
    }
}
/* This file was generated by scramble.py. */
