/* This file was generated by scramble.py. */
#line 1 "src/isometric.py"
#ifndef _ISOMETRIC_
#define _ISOMETRIC_
typedef struct Viewport Viewport;
#line 1
#include "common.h"
#line 13
struct Viewport {
    float x, y;
    float zoom;
};
Viewport* viewport_new(float w, float h);
#line 23
void viewport_update(Viewport * self, float w, float h);
#line 28
void project(Viewport * self, float x, float y, float z, float * sx, float * sy);
#line 34
void unproject(Viewport * self, float sx, float sy, float y, float * x, float * z);
#line 41
void unproject_y(Viewport * self, float sy, float x, float z, float * y);
#endif
/* This file was generated by scramble.py. */
