/* This file was generated by scramble.py. */
#line 1 "src/main.py"
#include "main.h"
#line 7
char * main_data_path;
static void cheat(char unichar);
#line 10
void main_switch_to_game(void) {
    All * a = global_a;
    a->title = 0;
    if (! game->state) {
        a->load_after_redraw = 1;
    }
}
#line 16
void main_switch_to_title(int com) {
    All * a = global_a;
    a->title = 1;
    title_com(com);
}
void all_init(All * self) {
    memset(self, 0, sizeof (* self));
    self->title = 1;
    self->FPS = 60;
#line 26
    self->font = NULL;
#line 28
    self->ftpos = 0;
    self->direct_speed_measure = self->FPS;
#line 32
    self->show_fps = 0;
}
void sound(LandSound * s, float vol) {
    All * a = global_a;
    land_sound_play(s, vol * a->sound / 6.0, 0, 1);
}
void add_time(void) {
    All * a = global_a;
    a->frame_times [a->ftpos] = land_get_time();
    a->ftpos += 1;
    if (a->ftpos >= a->FPS) {
        a->ftpos = 0;
    }
}
#line 45
void get_fps(double * average, double * minmax) {
    All * a = global_a;
    int prev = a->FPS - 1;
    double min_dt = 1;
    double max_dt = 1 / 1000000.0;
    double av = 0;
    for (int i = 0; i < a->FPS; i += 1) {
        if (i != a->ftpos) {
            double dt = a->frame_times [i] - a->frame_times [prev];
            if (dt < min_dt && dt > 0) {
                min_dt = dt;
            }
#line 56
            if (dt > max_dt) {
                max_dt = dt;
            }
#line 58
            av += dt;
        }
#line 59
        prev = i;
    }
#line 60
    av /= (double) a->FPS - 1;
    * average = ceil(1 / av);
    double d = 1 / min_dt - 1 / max_dt;
    * minmax = floor(d / 2);
}
void redraw(void) {
#line 67
    All * a = global_a;
#line 69
    if (a->load_after_redraw) {
        if (! a->overview) {
            render_loading_screen();
        }
#line 72
        if (a->load_after_redraw == 1) {
            a->load_after_redraw = 2;
        }
#line 74
        else if (a->load_after_redraw == 2) {
            // wait for logic code to advance
#line 74
            ;
        }
#line 77
        if (a->load_after_redraw > 2) {
            a->load_after_redraw++;
            double t = land_get_time();
            while (1) {
                if (! blocks_preload(game->blocks)) {
                    a->load_after_redraw = 0;
#line 84
                    if (a->overview) {
                        overview_render_next(game->overview);
                    }
#line 86
                    break;
                }
#line 87
                if (land_get_time() > t + 0.01) {
                    break;
                }
            }
        }
#line 90
        if (! a->overview) {
#line 90
            return ;
        }
    }
    float w = land_display_width();
    float h = land_display_height();
    //float fh = land_font_height(a->font)
#line 97
    if (a->title) {
        title_render();
    }
#line 98
    else {
#line 100
        render(game, w, h);
    }
    if (a->show_fps) {
        double f1, f2;
        get_fps(& f1, & f2);
        land_text_pos(w, 0);
        land_font_set(a->font);
        land_color(a->text.r, a->text.g, a->text.b, a->text.a);
        land_print_right("FPS: %4d +- %-4d", (int) f1, (int) f2);
        land_print_right("%4d / sec", (int)(1.0 / a->direct_speed_measure));
    }
}
#line 111
void reload_fonts(void) {
    LandBuffer * b = land_buffer_new();
    land_buffer_cat(b, main_data_path);
    //land_buffer_cat(b, "/data/Muli-Regular.ttf")
    land_buffer_cat(b, "/data/JosefinSans-Regular.ttf");
    char * path = land_buffer_finish(b);
#line 118
    All * a = global_a;
    float w = land_display_width();
    //float h = land_display_height()
    double s = w / 960;
#line 123
    if (a->font) {
        land_font_destroy(a->font);
    }
#line 125
    if (a->medium) {
        land_font_destroy(a->medium);
    }
#line 127
    if (a->big) {
        land_font_destroy(a->big);
    }
    a->font = land_font_load(path, 10 * s);
    land_font_scale(a->font, 1.0 / s);
    a->medium = land_font_load(path, 24 * s);
    land_font_scale(a->medium, 1.0 / s);
    a->big = land_font_load(path, 60 * s);
    land_font_scale(a->big, 1.0 / s);
#line 137
    land_font_set(a->medium);
    land_text_get_width("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");
#line 140
    land_free(path);
}
void init(void) {
    All * a = global_a;
    all_init(a);
    land_display_title("Yellow and Dangerous");
    reload_fonts();
#line 148
    a->up = 0;
    a->down = 0;
    a->left = 0;
    a->right = 0;
    a->jump = 0;
#line 154
    a->text = (LandColor) {0, 0, 0, 1};
#line 156
    config_controls_read();
#line 158
    title_init();
#line 160
    game_setup(land_display_width(), land_display_height());
#line 162
    render_setup();
#line 164
    a->show_fps = 0;
#line 166
    for (int i = 0; i < 10; i += 1) {
        a->cheatpos [i] = 0;
    }
}
#line 169
void done(void) {
    All * a = global_a;
    game_del(game);
    land_font_destroy(a->font);
}
void update(void) {
    All * a = global_a;
#line 177
    if (land_was_resized()) {
#line 179
        viewport_update(game->viewport, land_display_width(), land_display_height());
        a->resize_in_ticks = 10;
    }
    if (a->resize_in_ticks > 0) {
        a->resize_in_ticks--;
        if (a->resize_in_ticks == 0) {
            reload_fonts();
        }
    }
#line 187
    if (a->load_after_redraw) {
        if (a->load_after_redraw == 2) {
#line 190
            load_level(a->editor || game->record->is_replaying || game->record->is_recording, a->find_entrance);
            if (a->find_entrance) {
                a->find_entrance = 0;
                if (game->player) {
                    player_find_entrance(& game->player->super);
                }
            }
#line 195
            if (game && game->player) {
#line 197
                record_load(game->record, game->level, game->player->super.x, game->player->super.y, game->player->super.z);
            }
#line 198
            a->load_after_redraw++;
        }
#line 198
        return ;
    }
#line 201
    config_check_controls(a);
#line 203
    if (a->title) {
        title_tick();
    }
#line 204
    else {
#line 206
        game_tick(game);
    }
}
#line 208
void runner_init(LandRunner * self) {
    init();
}
void runner_done(LandRunner * self) {
    done();
}
static void cheat(char unichar) {
    All * a = global_a;
    char const * cheatcodes [] = {"iddqd", "idflower", "idkey"};
    for (int i = 0; i < 3; i += 1) {
        if (unichar == cheatcodes [i] [a->cheatpos [i]]) {
            a->cheatpos [i] += 1;
            if (a->cheatpos [i] == (int) strlen(cheatcodes [i])) {
                a->cheatpos [i] = 0;
                if (i == 0) {
                    a->godmode = ! a->godmode;
                }
#line 224
                if (i == 1) {
                    for (int j = 1; j < 8; j += 1) {
                        game->flower [j] = 1;
                        game->test_tube [j] = 1;
                    }
                }
#line 228
                if (i == 2) {
                    game->key = ! game->key;
                }
            }
        }
#line 229
        else {
#line 231
            a->cheatpos [i] = 0;
        }
    }
}
#line 233
void runner_update(LandRunner * self) {
    All * a = global_a;
#line 236
    update();
#line 238
    if (land_closebutton()) {
        save_level(0, 0);
        land_quit();
    }
    if (land_switched_out()) {
        save_level(0, 0);
    }
    if (land_was_halted()) {
#line 245
        ;
    }
#line 248
    if (! land_keybuffer_empty()) {
        int k, u;
        land_keybuffer_next(& k, & u);
        cheat(u);
#line 253
        if (k == LandKeyEscape) {
            save_level(0, 0);
            land_quit();
        }
#line 256
        else if (k == LandKeyFunction + 1) {
            a->show_fps = ! a->show_fps;
        }
#line 257
        else {
#line 259
            if (a->text_input) {
                if (u == '|') {
                    u = '\n';
                }
#line 262
                if (u == 13) {
                    u = 0;
                }
#line 264
                if (a->text_input == 1) {
                    game->title [a->cursor++] = u;
                }
#line 266
                else if (a->text_input == 2) {
                    game->hint [a->cursor++] = u;
                }
#line 268
                if (u == 0) {
                    a->text_input = 0;
                }
            }
#line 270
            else if (! a->title) {
                if (a->editor_enabled) {
                    game_key(game, k);
                }
            }
        }
    }
}
//elif k == 'm':
//    land_stream_set_playing(render_music,
//        not land_stream_is_playing(render_music))
#line 278
void runner_redraw(LandRunner * self) {
    All * a = global_a;
#line 281
    double t = - land_get_time();
    add_time();
#line 284
    redraw();
#line 286
    t += land_get_time();
    a->direct_speed_measure = t;
}
int my_main(void) {
    All * a;
    land_alloc(a);
#line 293
    int w = 960;
    int h = 600;
    a->show_help = 1;
#line 297
    land_init();
#line 299
    main_data_path = land_strdup(".");
#line 301
    if (land_argc > 1) {
        if (land_equals(land_argv [1], "test")) {
            return test();
        }
    }
    //land_set_display_parameters(w, h, LAND_OPENGL)
#line 306
    #ifdef ANDROID
#line 308
    land_set_display_parameters(0, 0, LAND_FULLSCREEN | LAND_DEPTH | LAND_LANDSCAPE);
#line 308
    #else
#line 310
    land_set_display_parameters(w, h, LAND_DEPTH | LAND_RESIZE);
#line 310
    #endif
#line 318
    LandRunner * game_runner = land_runner_new("Yellow and Dangerous", runner_init, NULL, runner_update, runner_redraw, NULL, runner_done);
    a->w = w;
    a->h = h;
#line 322
    land_runner_register(game_runner);
    land_set_initial_runner(game_runner);
    land_mainloop();
#line 326
    land_free(main_data_path);
    land_free(a);
#line 329
    return 0;
}
land_use_main(my_main);
/* This file was generated by scramble.py. */
