/* This file was generated by scramble.py. */
#line 1 "src/platform.py"
#ifndef _PLATFORM_
#define _PLATFORM_
typedef struct Platform Platform;
#line 1
#include "common.h"
#include "block.h"
#line 2
#include "render.h"
#line 4
struct Platform {
    Block super;
    bool moving;
    int wait;
    float last_y, last_last_y;
};
Block* platform_allocate(void);
#line 15
void platform_tick(Block * super);
#line 48
void platform_touch(Block * super, Block * other, float dx, float dy, float dz);
#line 59
void stop(Block * super);
#endif
/* This file was generated by scramble.py. */
