/* This file was generated by scramble.py. */
#line 1 "src/record.py"
#ifndef _RECORD_
#define _RECORD_
typedef struct Bitstream Bitstream;
typedef struct Record Record;
#line 1
#include "common.h"
#include "save.h"
#line 4
struct Bitstream {
    int n;
    char * b;
    int acc;
    int bit;
};
void bitstream_add_bit(Bitstream * self, int x);
#line 20
int bitstream_get_bit(Bitstream * self, int t);
#line 25
void bitstream_finish(Bitstream * self);
#line 29
struct Record {
    Bitstream inputs [5];
    bool is_recording;
    bool is_replaying;
    bool wait_on_level;
    int tick;
#line 36
    int level;
    int x, y, z;
};
Record* record_new(void);
#line 43
void record_destroy(Record * self);
#line 65
void record_tick(Record * self);
#line 73
void record_start(Record * self, int level, int x, int y, int z);
#line 86
void record_done(Record * self);
#line 108
void record_clear(Record * self);
#line 114
void record_set_recording(Record * self);
#line 121
void record_set_replaying(Record * self);
#line 134
void replay_done(Record * self);
#line 141
void record_load(Record * self, int level, int x, int y, int z);
#line 147
void replay_start(Record * self, int level, int x, int y, int z);
#endif
/* This file was generated by scramble.py. */
