/* This file was generated by scramble.py. */
#line 1 "src/record.py"
#include "record.h"
static void recording_tick(Record * self);
static void replaying_tick(Record * self);
static void record_get_name(Record * self, char * out);
#line 10
void bitstream_add_bit(Bitstream * self, int x) {
    self->acc += x << self->bit;
    self->bit++;
    if (self->bit == 8) {
        self->b = land_realloc(self->b, self->n + 1);
        self->b [self->n] = self->acc;
        self->n++;
        self->bit = 0;
        self->acc = 0;
    }
}
#line 20
int bitstream_get_bit(Bitstream * self, int t) {
    int n = t >> 3;
    int bit = t & 7;
    return (self->b [n] >> bit) & 1;
}
void bitstream_finish(Bitstream * self) {
    while (self->bit != 0) {
        bitstream_add_bit(self, 0);
    }
}
#line 39
Record* record_new(void) {
    Record * r;
#line 40
    land_alloc(r);
    return r;
}
void record_destroy(Record * self) {
    for (int i = 0; i < 5; i += 1) {
        land_free(self->inputs [i].b);
    }
#line 46
    land_free(self);
}
static void recording_tick(Record * self) {
    All * a = global_a;
    bool rcontrols [5] = {a->left, a->right, a->up, a->down, a->jump};
#line 52
    for (int i = 0; i < 5; i += 1) {
        bitstream_add_bit(& self->inputs [i], rcontrols [i] ? 1 : 0);
    }
}
#line 55
static void replaying_tick(Record * self) {
    All * a = global_a;
    bool * rcontrols [5] = {& a->left, & a->right, & a->up, & a->down, & a->jump};
    for (int i = 0; i < 5; i += 1) {
        int bit = bitstream_get_bit(& self->inputs [i], self->tick);
        * (rcontrols [i]) = bit;
    }
#line 61
    self->tick++;
    if (self->tick >= self->inputs [0].n * 8) {
        self->is_replaying = 0;
    }
}
#line 65
void record_tick(Record * self) {
    if (self->wait_on_level) {
#line 66
        return ;
    }
    if (self->is_recording) {
        recording_tick(self);
    }
#line 70
    if (self->is_replaying) {
        replaying_tick(self);
    }
}
#line 73
void record_start(Record * self, int level, int x, int y, int z) {
    if (! self->is_recording) {
#line 74
        return ;
    }
#line 77
    self->x = x;
    self->y = y;
    self->z = z;
    self->level = level;
    char name [1024];
    record_get_name(self, name);
    print("recording start %s", name);
    self->wait_on_level = 0;
}
void record_done(Record * self) {
    if (self->is_replaying) {
        replay_done(self);
    }
#line 89
    if (! self->is_recording) {
#line 89
        return ;
    }
    if (self->wait_on_level) {
#line 91
        return ;
    }
    self->is_recording = 0;
    for (int i = 0; i < 5; i += 1) {
        bitstream_finish(& self->inputs [i]);
    }
#line 96
    char name [1024];
    record_get_name(self, name);
    LandBuffer * b = land_buffer_new();
    land_buffer_add_uint32_t(b, self->inputs [0].n);
    for (int i = 0; i < 5; i += 1) {
        land_buffer_add(b, self->inputs [i].b, self->inputs [i].n);
    }
#line 102
    land_buffer_compress(b);
    land_buffer_write_to_file(b, name);
    land_buffer_destroy(b);
    record_clear(self);
    print("record_done %s", name);
}
void record_clear(Record * self) {
    for (int i = 0; i < 5; i += 1) {
        self->inputs [i].n = 0;
        self->inputs [i].acc = 0;
        self->inputs [i].bit = 0;
    }
}
#line 114
void record_set_recording(Record * self) {
    print("record_set_recording");
    self->is_replaying = 0;
    self->is_recording = 1;
    self->wait_on_level = 1;
    record_clear(self);
}
void record_set_replaying(Record * self) {
    print("record_set_replaying");
    self->is_replaying = 1;
    self->is_recording = 0;
    self->wait_on_level = 1;
    record_clear(self);
}
static void record_get_name(Record * self, char * out) {
    char suffix [1024];
#line 131
    sprintf(suffix, "_%04d%04d%04d.gz", self->x + 22 * 24, self->y + 4 * 24, self->z + 22 * 24);
    save_get_name("record", self->level, suffix, out);
}
void replay_done(Record * self) {
    if (! self->is_replaying) {
#line 135
        return ;
    }
    if (self->wait_on_level) {
#line 137
        return ;
    }
    self->is_replaying = 0;
}
void record_load(Record * self, int level, int x, int y, int z) {
    if (self->is_recording) {
        record_start(self, level, x, y, z);
    }
#line 144
    if (self->is_replaying) {
        replay_start(self, level, x, y, z);
    }
}
#line 147
void replay_start(Record * self, int level, int x, int y, int z) {
    if (! self->is_replaying) {
#line 148
        return ;
    }
    char name [1024];
    self->x = x;
    self->y = y;
    self->z = z;
    self->level = level;
    record_get_name(self, name);
    LandBuffer * b = land_buffer_read_from_file(name);
    if (! b) {
        print("could not replay %s", name);
#line 158
        return ;
    }
    land_buffer_decompress(b);
    int n = land_buffer_get_uint32_t(b, 0);
    for (int i = 0; i < 5; i += 1) {
        Bitstream * bs = self->inputs + i;
        bs->b = land_realloc(bs->b, n);
        bs->n = n;
        memcpy(bs->b, b->buffer + 4 + i * n, n);
    }
#line 167
    land_buffer_destroy(b);
    self->tick = 0;
    print("record_load %s (%d ticks)", name, n * 8);
    self->wait_on_level = 0;
}
/* This file was generated by scramble.py. */
