/* This file was generated by scramble.py. */
#line 1 "src/render.py"
#include "render.h"
#line 26
Render r;
LandImage * Render_Smoke;
//static int filter(char const *name, bool is_dir, void *data):
//    if is_dir: return 0
//    return 1
static LandImage* loadpic(char const * name);
static BlockType* render_load(char const * name, float x, float y, float z, bool dynamic, bool lift, bool transparent, bool fixed, int frames, bool animated);
static LandSound* render_loads(char const * name);
static void draw_move_controls(void);
static void draw_jump_controls(void);
static void draw_pause_controls(void);
#line 33
static LandImage* loadpic(char const * name) {
    LandBuffer * b = land_buffer_new();
    land_buffer_cat(b, r.path);
    land_buffer_cat(b, name);
    char * path = land_buffer_finish(b);
    LandImage * i = land_image_load(path);
    land_free(path);
    land_image_center(i);
    return i;
}
#line 45
static BlockType* render_load(char const * name, float x, float y, float z, bool dynamic, bool lift, bool transparent, bool fixed, int frames, bool animated) {
    BlockType * bt = NULL;
    float ss = 96;
#line 50
    bt = blocktype_new(name, ss * x, ss * y, ss * z, block_tick, block_touch, block_destroy, block_allocate, block_post_init);
    bt->dynamic = dynamic;
    bt->lift = lift;
    bt->transparent = transparent;
    bt->fixed = fixed;
    bt->animated = animated || dynamic;
    //LandArray *frames
#line 58
    LandBuffer * b = land_buffer_new();
    land_buffer_cat(b, r.path);
    land_buffer_cat(b, name);
    char * path = land_buffer_finish(b);
    // doesn't work on Android
    //frames = land_filelist(path, filter, LAND_FULL_PATH, None)
    //if not frames:
    //    print("Could not find %s%s", path, name)
    //land_array_sort_alphabetical(frames)
    //for char *s in LandArray *frames:
#line 71
    for (int fi = 1; fi < frames + 1; fi += 1) {
        char s [1024];
        char section [1024];
        sprintf(s, "%s/%04d.png", path, fi);
        sprintf(section, "%s/%04d.png", name, fi);
        //LandImage *pic = land_image_load(s)
        LandImage * pic = land_image_new_deferred(s);
        pic->x = land_ini_get_int(r.offsets, section, "x", 0);
        pic->y = land_ini_get_int(r.offsets, section, "y", 0);
        //pic.flags |= LAND_IMAGE_CENTER
        if (! pic) {
            // or not (pic.flags & LAND_LOADED):
#line 82
            print("Could not load %s", s);
            break;
        }
#line 83
        else {
#line 85
            if (! bt->bitmaps) {
                bt->bitmaps = land_array_new();
            }
            //bt->x = -land_image_width(pic) / 4
            //bt->y = -land_image_height(pic) / 4
#line 89
            land_array_add(bt->bitmaps, pic);
        }
    }
    //land_free(s)
#line 91
    land_free(path);
    //land_array_destroy(frames)
    return bt;
}
BlockType * Render_Block;
#line 95
BlockType * Render_BlockBottom;
#line 95
BlockType * Render_BlockLeft;
#line 95
BlockType * Render_BlockBottom2;
#line 95
BlockType * Render_BlockBottom3;
#line 95
BlockType * Render_BlockBottomLeft3;
#line 95
BlockType * Render_PlankRight;
#line 95
BlockType * Render_PlankLeft;
#line 95
BlockType * Render_BlockLeft2;
#line 95
BlockType * Render_BlockRight2;
#line 95
BlockType * Render_Scientist;
#line 95
BlockType * Render_Cube2;
#line 95
BlockType * Render_Plate;
#line 95
BlockType * Render_Cube3;
#line 95
BlockType * Render_Barrel;
#line 95
BlockType * Render_TreeBottom;
#line 95
BlockType * Render_TreeTop;
#line 95
BlockType * Render_Trunk;
#line 95
BlockType * Render_ExitLeft;
#line 95
BlockType * Render_ExitRight;
#line 95
BlockType * Render_Allefant;
#line 95
BlockType * Render_WindowRight;
#line 95
BlockType * Render_WindowLeft;
#line 95
BlockType * Render_BlockSmall3;
#line 95
BlockType * Render_CherryTree;
#line 95
BlockType * Render_Waypoint;
#line 95
BlockType * Render_Crate;
#line 95
BlockType * Render_BlockLeft3;
#line 95
BlockType * Render_BlockRight3;
#line 95
BlockType * Render_Plant;
#line 95
BlockType * Render_Platform;
#line 95
BlockType * Render_LeverLeft;
#line 95
BlockType * Render_LeverRight;
#line 95
BlockType * Render_Statue;
#line 95
BlockType * Render_RampLeft;
#line 95
BlockType * Render_RampRight;
#line 95
BlockType * Render_VentLeft;
#line 95
BlockType * Render_VentRight;
#line 95
BlockType * Render_BlockSmall;
#line 95
BlockType * Render_BlockRight;
#line 95
BlockType * Render_BlockSmallLeft;
#line 95
BlockType * Render_BlockSmallRight;
#line 95
BlockType * Render_Gentian;
#line 95
BlockType * Render_Eye;
#line 95
BlockType * Render_Ginko;
#line 95
BlockType * Render_Edelweiss;
#line 95
BlockType * Render_Cart;
#line 95
BlockType * Render_GrateBottom;
#line 95
BlockType * Render_GrateLeft;
#line 95
BlockType * Render_GrateRight;
#line 95
BlockType * Render_Gremlin;
#line 95
BlockType * Render_InvisibleLeft;
#line 95
BlockType * Render_InvisibleRight;
#line 95
BlockType * Render_Orchid;
#line 95
BlockType * Render_Sunflower;
#line 95
BlockType * Render_Hyacinth;
#line 95
BlockType * Render_DeskLeft;
#line 95
BlockType * Render_WallLeft;
#line 95
BlockType * Render_WallRight;
#line 95
BlockType * Render_DeskRight;
#line 95
BlockType * Render_Floor;
#line 95
BlockType * Render_TestTube;
#line 95
BlockType * Render_Rose;
#line 95
BlockType * Render_Belladonna;
#line 95
BlockType * Render_BridgeRight;
#line 95
BlockType * Render_BridgeLeft;
#line 95
BlockType * Render_Car;
#line 95
BlockType * Render_Key;
#line 95
BlockType * Render_BlockBottomRight3;
#line 95
BlockType * Render_ConveyorLeft;
#line 95
BlockType * Render_ConveyorRight;
#line 95
LandSound * Render_step;
#line 95
LandSound * Render_push;
#line 95
LandSound * Render_off;
#line 95
LandSound * Render_on;
#line 95
LandSound * Render_uhg;
#line 95
LandSound * Render_oh_no;
#line 95
LandSound * Render_teleport;
#line 95
LandSound * Render_glass;
#line 95
LandSound * Render_metal;
#line 95
LandSound * Render_ignition;
#line 95
LandSound * Render_pickup;
#line 194
static LandSound* render_loads(char const * name) {
    LandBuffer * b = land_buffer_new();
    land_buffer_cat(b, main_data_path);
    land_buffer_cat(b, "/data/");
    land_buffer_cat(b, name);
    land_buffer_cat(b, ".ogg");
    char * fpath = land_buffer_finish(b);
    LandSound * s = land_sound_load(fpath);
    land_free(fpath);
    if (! s) {
        print("Could not load %s", fpath);
    }
#line 205
    return s;
}
void render_loading_screen(void) {
    land_clear(1, 1, 1, 1);
    land_clear_depth(1);
    land_reset_transform();
    float w = land_display_width();
    float h = land_display_height();
    land_scale(w / 960, w / 960);
    land_text_pos(960 / 2, (h / (w / 960)) / 2 - 10);
    land_font_set(global_a->medium);
    land_color(0, 0, 0, 1);
    land_print_center("%s", "Loading! Please Wait!");
}
void render_ad_screen(void) {
    land_clear(1, 1, 1, 1);
    land_clear_depth(1);
    land_reset_transform();
    float w = land_display_width();
    float h = land_display_height();
    land_scale(w / 960, w / 960);
    land_text_pos(960 / 2, (h / (w / 960)) / 2 - 10);
    land_font_set(global_a->medium);
    land_color(0, 0, 0, 1);
    land_print_center("Displaying ad!");
}
void render_setup(void) {
    if (r.was_setup) {
#line 232
        return ;
    }
#line 233
    r.was_setup = 1;
#line 235
    land_render_state(LAND_ALPHA_TEST, 1);
    land_render_state(LAND_ALPHA_FUNCTION, LAND_GREATER);
    land_render_state(LAND_ALPHA_VALUE, 0);
#line 239
    r.background_color = (LandColor) {1, 1, 1, 1};
#line 241
    render_setup_path();
#line 243
    render_loading_screen();
    land_flip();
#line 246
    r.music = land_stream_new(2048, 4, 22050, 16, 2);
#line 248
    load_info();
#line 250
    play_song();
#line 252
    Render_Smoke = loadpic("../smoke.png");
#line 254
    Render_step = render_loads("step");
#line 254
    Render_push = render_loads("push");
#line 254
    Render_off = render_loads("off");
#line 254
    Render_on = render_loads("on");
#line 254
    Render_uhg = render_loads("uhg");
#line 254
    Render_oh_no = render_loads("oh no");
#line 254
    Render_teleport = render_loads("teleport");
#line 254
    Render_glass = render_loads("glass");
#line 254
    Render_metal = render_loads("metal");
#line 254
    Render_ignition = render_loads("ignition");
#line 254
    Render_pickup = render_loads("pickup");
#line 259
    render_load_blocktypes();
}
void render_setup_path(void) {
    if (r.path) {
        land_free(r.path);
    }
#line 264
    LandBuffer * b = land_buffer_new();
    land_buffer_cat(b, main_data_path);
    land_buffer_cat(b, "/data/yellowanddangerous/");
    r.path = land_buffer_finish(b);
}
void render_load_blocktypes(void) {
#line 271
    char * ini = land_strdup(r.path);
    land_concatenate(& ini, "/offsets.ini");
    r.offsets = land_ini_read(ini);
    land_free(ini);
#line 276
    block_types = land_array_new();
    Render_Block = render_load("Block", 2, 2, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Block);
#line 277
    Render_BlockBottom = render_load("BlockBottom", 2, 0.5, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockBottom);
#line 277
    Render_BlockLeft = render_load("BlockLeft", 0.5, 2, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockLeft);
#line 277
    Render_BlockBottom2 = render_load("BlockBottom2", 2, 1, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockBottom2);
#line 277
    Render_BlockBottom3 = render_load("BlockBottom3", 2, 0.5, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockBottom3);
#line 277
    Render_BlockBottomLeft3 = render_load("BlockBottomLeft3", 2, 0.5, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockBottomLeft3);
#line 277
    Render_PlankRight = render_load("PlankRight", 1.9, 0.245, 0.5, 1, 1, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_PlankRight);
#line 277
    Render_PlankLeft = render_load("PlankLeft", 0.5, 0.245, 1.9, 1, 1, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_PlankLeft);
#line 277
    Render_BlockLeft2 = render_load("BlockLeft2", 1, 2, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockLeft2);
#line 277
    Render_BlockRight2 = render_load("BlockRight2", 2, 2, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockRight2);
#line 277
    Render_Scientist = render_load("Scientist", 0.75, 1.75, 0.75, 1, 0, 0, 0, 128, 0);
#line 277
    land_array_add(block_types, Render_Scientist);
#line 277
    Render_Cube2 = render_load("Cube2", 1, 1, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Cube2);
#line 277
    Render_Plate = render_load("Plate", 1, 0.25, 1, 0, 0, 0, 0, 2, 0);
#line 277
    land_array_add(block_types, Render_Plate);
#line 277
    Render_Cube3 = render_load("Cube3", 0.667, 0.667, 0.667, 1, 1, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Cube3);
#line 277
    Render_Barrel = render_load("Barrel", 0.8, 1.2, 0.8, 1, 0, 0, 0, 3, 0);
#line 277
    land_array_add(block_types, Render_Barrel);
#line 277
    Render_TreeBottom = render_load("TreeBottom", 2, 2, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_TreeBottom);
#line 277
    Render_TreeTop = render_load("TreeTop", 2, 2, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_TreeTop);
#line 277
    Render_Trunk = render_load("Trunk", 0.2, 1.0, 0.2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Trunk);
#line 277
    Render_ExitLeft = render_load("ExitLeft", 1, 0.25, 2, 0, 0, 0, 0, 5, 0);
#line 277
    land_array_add(block_types, Render_ExitLeft);
#line 277
    Render_ExitRight = render_load("ExitRight", 2, 0.25, 1, 0, 0, 0, 0, 5, 0);
#line 277
    land_array_add(block_types, Render_ExitRight);
#line 277
    Render_Allefant = render_load("Allefant", 1.25, 1.75, 1.25, 1, 0, 0, 0, 64, 0);
#line 277
    land_array_add(block_types, Render_Allefant);
#line 277
    Render_WindowRight = render_load("WindowRight", 2, 2, 0.25, 0, 0, 1, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_WindowRight);
#line 277
    Render_WindowLeft = render_load("WindowLeft", 0.25, 2, 2, 0, 0, 1, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_WindowLeft);
#line 277
    Render_BlockSmall3 = render_load("BlockSmall3", 1, 0.5, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockSmall3);
#line 277
    Render_CherryTree = render_load("CherryTree", 3, 5, 3, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_CherryTree);
#line 277
    Render_Waypoint = render_load("Waypoint", 0.5, 0, 0.5, 0, 0, 0, 0, 10, 0);
#line 277
    land_array_add(block_types, Render_Waypoint);
#line 277
    Render_Crate = render_load("Crate", 0.95, 2, 0.95, 1, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Crate);
#line 277
    Render_BlockLeft3 = render_load("BlockLeft3", 0.5, 1, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockLeft3);
#line 277
    Render_BlockRight3 = render_load("BlockRight3", 2, 1, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockRight3);
#line 277
    Render_Plant = render_load("Plant", 0.5, 0.5, 0.5, 1, 1, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Plant);
#line 277
    Render_Platform = render_load("Platform", 2, 0.5, 2, 1, 0, 0, 1, 6, 0);
#line 277
    land_array_add(block_types, Render_Platform);
#line 277
    Render_LeverLeft = render_load("LeverLeft", 0.5, 2, 1, 0, 0, 0, 0, 2, 0);
#line 277
    land_array_add(block_types, Render_LeverLeft);
#line 277
    Render_LeverRight = render_load("LeverRight", 1, 2, 0.5, 0, 0, 0, 0, 2, 0);
#line 277
    land_array_add(block_types, Render_LeverRight);
#line 277
    Render_Statue = render_load("Statue", 2, 2, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Statue);
#line 277
    Render_RampLeft = render_load("RampLeft", 1, 0.5, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_RampLeft);
#line 277
    Render_RampRight = render_load("RampRight", 2, 0.5, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_RampRight);
#line 277
    Render_VentLeft = render_load("VentLeft", 0.5, 2, 1, 0, 0, 0, 0, 4, 1);
#line 277
    land_array_add(block_types, Render_VentLeft);
#line 277
    Render_VentRight = render_load("VentRight", 1, 2, 0.5, 0, 0, 0, 0, 4, 1);
#line 277
    land_array_add(block_types, Render_VentRight);
#line 277
    Render_BlockSmall = render_load("BlockSmall", 1, 0.5, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockSmall);
#line 277
    Render_BlockRight = render_load("BlockRight", 2, 2, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockRight);
#line 277
    Render_BlockSmallLeft = render_load("BlockSmallLeft", 0.5, 1, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockSmallLeft);
#line 277
    Render_BlockSmallRight = render_load("BlockSmallRight", 1, 1, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockSmallRight);
#line 277
    Render_Gentian = render_load("Gentian", 0.5, 0.5, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Gentian);
#line 277
    Render_Eye = render_load("Eye", 0.5, 0.5, 0.5, 1, 1, 0, 0, 8, 0);
#line 277
    land_array_add(block_types, Render_Eye);
#line 277
    Render_Ginko = render_load("Ginko", 2, 4, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Ginko);
#line 277
    Render_Edelweiss = render_load("Edelweiss", 0.5, 0.5, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Edelweiss);
#line 277
    Render_Cart = render_load("Cart", 2, 1.25, 2, 1, 0, 0, 0, 4, 0);
#line 277
    land_array_add(block_types, Render_Cart);
#line 277
    Render_GrateBottom = render_load("GrateBottom", 2, 0.25, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_GrateBottom);
#line 277
    Render_GrateLeft = render_load("GrateLeft", 0.25, 2, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_GrateLeft);
#line 277
    Render_GrateRight = render_load("GrateRight", 2, 2, 0.25, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_GrateRight);
#line 277
    Render_Gremlin = render_load("Gremlin", 0.5, 0.5, 0.5, 1, 0, 0, 0, 16, 0);
#line 277
    land_array_add(block_types, Render_Gremlin);
#line 277
    Render_InvisibleLeft = render_load("InvisibleLeft", 0.25, 4, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_InvisibleLeft);
#line 277
    Render_InvisibleRight = render_load("InvisibleRight", 2, 4, 0.25, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_InvisibleRight);
#line 277
    Render_Orchid = render_load("Orchid", 0.5, 1.25, 0.75, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Orchid);
#line 277
    Render_Sunflower = render_load("Sunflower", 1, 2.5, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Sunflower);
#line 277
    Render_Hyacinth = render_load("Hyacinth", 0.5, 1, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Hyacinth);
#line 277
    Render_DeskLeft = render_load("DeskLeft", 1, 1, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_DeskLeft);
#line 277
    Render_WallLeft = render_load("WallLeft", 0.5, 3, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_WallLeft);
#line 277
    Render_WallRight = render_load("WallRight", 2, 3, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_WallRight);
#line 277
    Render_DeskRight = render_load("DeskRight", 2, 1, 1, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_DeskRight);
#line 277
    Render_Floor = render_load("Floor", 2, 0.25, 2, 0, 0, 0, 0, 2, 0);
#line 277
    land_array_add(block_types, Render_Floor);
#line 277
    Render_TestTube = render_load("TestTube", 0.125, 0.5, 0.125, 1, 1, 0, 0, 7, 0);
#line 277
    land_array_add(block_types, Render_TestTube);
#line 277
    Render_Rose = render_load("Rose", 0.5, 1, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Rose);
#line 277
    Render_Belladonna = render_load("Belladonna", 0.5, 1.5, 0.5, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Belladonna);
#line 277
    Render_BridgeRight = render_load("BridgeRight", 2.5, 0.25, 0.5, 1, 1, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BridgeRight);
#line 277
    Render_BridgeLeft = render_load("BridgeLeft", 0.5, 0.25, 2.5, 1, 1, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BridgeLeft);
#line 277
    Render_Car = render_load("Car", 2, 2, 3, 0, 0, 0, 0, 2, 0);
#line 277
    land_array_add(block_types, Render_Car);
#line 277
    Render_Key = render_load("Key", 0.5, 0.5, 0.5, 1, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_Key);
#line 277
    Render_BlockBottomRight3 = render_load("BlockBottomRight3", 1, 0.5, 2, 0, 0, 0, 0, 1, 0);
#line 277
    land_array_add(block_types, Render_BlockBottomRight3);
#line 277
    Render_ConveyorLeft = render_load("ConveyorLeft", 1, 0.5, 2, 0, 0, 0, 0, 4, 1);
#line 277
    land_array_add(block_types, Render_ConveyorLeft);
#line 277
    Render_ConveyorRight = render_load("ConveyorRight", 2, 0.5, 1, 0, 0, 0, 0, 4, 1);
#line 277
    land_array_add(block_types, Render_ConveyorRight);
#line 284
    int i = 0;
    {
#line 285
        LandArrayIterator __iter0__ = LandArrayIterator_first(block_types);
#line 285
        for (BlockType * bt = LandArrayIterator_item(block_types, &__iter0__); LandArrayIterator_next(block_types, &__iter0__); bt = LandArrayIterator_item(block_types, &__iter0__)) {
            bt->btid = i++;
        }
    }
#line 288
    Render_InvisibleLeft->invisible = 1;
    Render_InvisibleRight->invisible = 1;
#line 291
    Render_Scientist->tick = player_tick;
    Render_Scientist->touch = player_touch;
    Render_Scientist->destroy = player_destroy;
    Render_Scientist->allocate = player_allocate;
    Render_Scientist->post_init = player_init;
    Render_Allefant->tick = allefant_tick;
    Render_Allefant->touch = allefant_touch;
    Render_Allefant->allocate = allefant_allocate;
    Render_Allefant->post_init = allefant_init;
    Render_Allefant->destroy = allefant_destroy;
    Render_Cube3->touch = cube_touch;
    Render_Barrel->touch = barrel_touch;
    Render_VentLeft->tick = vent_tick;
    Render_VentLeft->allocate = vent_allocate;
    Render_VentRight->tick = vent_tick;
    Render_VentRight->allocate = vent_allocate;
    Render_Platform->allocate = platform_allocate;
    Render_Platform->tick = platform_tick;
    Render_Platform->touch = platform_touch;
    Render_Eye->tick = eye_tick;
    Render_Cart->tick = cart_tick;
    Render_Gremlin->tick = gremlin_tick;
    Render_Gremlin->touch = gremlin_touch;
    Render_Gremlin->allocate = gremlin_allocate;
    Render_TestTube->touch = testtube_touch;
    Render_TestTube->tick = testtube_tick;
    Render_ConveyorLeft->tick = conveyor_tick;
    Render_ConveyorLeft->allocate = conveyor_allocate;
    Render_ConveyorRight->tick = conveyor_tick;
    Render_ConveyorRight->allocate = conveyor_allocate;
}
void play_song(void) {
    if (! r.music) {
#line 323
        return ;
    }
#line 326
    All * a = global_a;
    LandBuffer * b = land_buffer_new();
    land_buffer_cat(b, main_data_path);
#line 330
    if (r.song == 0) {
        land_buffer_cat(b, "/data/Manic Polka.ogg");
    }
#line 332
    else if (r.song == 1) {
        land_buffer_cat(b, "/data/katyusha.ogg");
    }
#line 334
    else if (r.song == 2) {
        land_buffer_cat(b, "/data/Overcast.ogg");
    }
#line 336
    else if (r.song == 3) {
        land_buffer_cat(b, "/data/allefant.ogg");
    }
#line 338
    else if (r.song == 4) {
        land_buffer_cat(b, "/data/Pixel Peeker Polka.ogg");
    }
#line 340
    else if (r.song == 5) {
        land_buffer_cat(b, "/data/fairy.ogg");
    }
#line 342
    char * musicpath = land_buffer_finish(b);
    land_stream_music(r.music, musicpath);
    land_free(musicpath);
    land_stream_volume(r.music, a->music / 6.0);
#line 347
    r.song++;
    if (r.song == 6) {
        r.song = 0;
    }
}
#line 351
void song_volume(void) {
    All * a = global_a;
    land_stream_volume(r.music, a->music / 6.0);
}
void render_teardown(void) {
    blocktype_destroy(Render_Block);
#line 356
    blocktype_destroy(Render_BlockBottom);
#line 356
    blocktype_destroy(Render_BlockLeft);
#line 356
    blocktype_destroy(Render_BlockBottom2);
#line 356
    blocktype_destroy(Render_BlockBottom3);
#line 356
    blocktype_destroy(Render_BlockBottomLeft3);
#line 356
    blocktype_destroy(Render_PlankRight);
#line 356
    blocktype_destroy(Render_PlankLeft);
#line 356
    blocktype_destroy(Render_BlockLeft2);
#line 356
    blocktype_destroy(Render_BlockRight2);
#line 356
    blocktype_destroy(Render_Scientist);
#line 356
    blocktype_destroy(Render_Cube2);
#line 356
    blocktype_destroy(Render_Plate);
#line 356
    blocktype_destroy(Render_Cube3);
#line 356
    blocktype_destroy(Render_Barrel);
#line 356
    blocktype_destroy(Render_TreeBottom);
#line 356
    blocktype_destroy(Render_TreeTop);
#line 356
    blocktype_destroy(Render_Trunk);
#line 356
    blocktype_destroy(Render_ExitLeft);
#line 356
    blocktype_destroy(Render_ExitRight);
#line 356
    blocktype_destroy(Render_Allefant);
#line 356
    blocktype_destroy(Render_WindowRight);
#line 356
    blocktype_destroy(Render_WindowLeft);
#line 356
    blocktype_destroy(Render_BlockSmall3);
#line 356
    blocktype_destroy(Render_CherryTree);
#line 356
    blocktype_destroy(Render_Waypoint);
#line 356
    blocktype_destroy(Render_Crate);
#line 356
    blocktype_destroy(Render_BlockLeft3);
#line 356
    blocktype_destroy(Render_BlockRight3);
#line 356
    blocktype_destroy(Render_Plant);
#line 356
    blocktype_destroy(Render_Platform);
#line 356
    blocktype_destroy(Render_LeverLeft);
#line 356
    blocktype_destroy(Render_LeverRight);
#line 356
    blocktype_destroy(Render_Statue);
#line 356
    blocktype_destroy(Render_RampLeft);
#line 356
    blocktype_destroy(Render_RampRight);
#line 356
    blocktype_destroy(Render_VentLeft);
#line 356
    blocktype_destroy(Render_VentRight);
#line 356
    blocktype_destroy(Render_BlockSmall);
#line 356
    blocktype_destroy(Render_BlockRight);
#line 356
    blocktype_destroy(Render_BlockSmallLeft);
#line 356
    blocktype_destroy(Render_BlockSmallRight);
#line 356
    blocktype_destroy(Render_Gentian);
#line 356
    blocktype_destroy(Render_Eye);
#line 356
    blocktype_destroy(Render_Ginko);
#line 356
    blocktype_destroy(Render_Edelweiss);
#line 356
    blocktype_destroy(Render_Cart);
#line 356
    blocktype_destroy(Render_GrateBottom);
#line 356
    blocktype_destroy(Render_GrateLeft);
#line 356
    blocktype_destroy(Render_GrateRight);
#line 356
    blocktype_destroy(Render_Gremlin);
#line 356
    blocktype_destroy(Render_InvisibleLeft);
#line 356
    blocktype_destroy(Render_InvisibleRight);
#line 356
    blocktype_destroy(Render_Orchid);
#line 356
    blocktype_destroy(Render_Sunflower);
#line 356
    blocktype_destroy(Render_Hyacinth);
#line 356
    blocktype_destroy(Render_DeskLeft);
#line 356
    blocktype_destroy(Render_WallLeft);
#line 356
    blocktype_destroy(Render_WallRight);
#line 356
    blocktype_destroy(Render_DeskRight);
#line 356
    blocktype_destroy(Render_Floor);
#line 356
    blocktype_destroy(Render_TestTube);
#line 356
    blocktype_destroy(Render_Rose);
#line 356
    blocktype_destroy(Render_Belladonna);
#line 356
    blocktype_destroy(Render_BridgeRight);
#line 356
    blocktype_destroy(Render_BridgeLeft);
#line 356
    blocktype_destroy(Render_Car);
#line 356
    blocktype_destroy(Render_Key);
#line 356
    blocktype_destroy(Render_BlockBottomRight3);
#line 356
    blocktype_destroy(Render_ConveyorLeft);
#line 356
    blocktype_destroy(Render_ConveyorRight);
#line 356
    land_sound_destroy(Render_step);
#line 356
    land_sound_destroy(Render_push);
#line 356
    land_sound_destroy(Render_off);
#line 356
    land_sound_destroy(Render_on);
#line 356
    land_sound_destroy(Render_uhg);
#line 356
    land_sound_destroy(Render_oh_no);
#line 356
    land_sound_destroy(Render_teleport);
#line 356
    land_sound_destroy(Render_glass);
#line 356
    land_sound_destroy(Render_metal);
#line 356
    land_sound_destroy(Render_ignition);
#line 356
    land_sound_destroy(Render_pickup);
#line 364
    land_stream_destroy(r.music);
    land_free(r.path);
}
static void draw_move_controls(void) {
    All * a = global_a;
    float w = land_display_width();
    float h = land_display_height();
    if (a->swipej && a->dpad > 3) {
        land_color(0.8, 0.1, 0, 0.5);
    }
#line 372
    else {
#line 374
        land_color(0.5, 0.4, 0, 0.5);
    }
#line 375
    float rr = w / 8 * 0.8;
#line 377
    if (a->dpad == 2 || a->dpad == 3) {
        rr *= 1.5;
    }
#line 379
    float rx = rr;
    float ry = h - rr;
#line 382
    if (a->dpad > 3) {
        if (! a->swipe) {
#line 383
            return ;
        }
        rx = a->swipex;
        ry = a->swipey;
    }
#line 387
    else if (a->dpad == 1 || a->dpad == 3) {
        rx = w - rr;
    }
    float xy [2 * 34];
    xy [0] = rx;
    xy [1] = ry;
    for (int i = 1; i < 34; i += 1) {
        double c = cos((i - 1.5) * pi / 16);
        double s = sin((i - 1.5) * pi / 16);
        float r2 = rr;
        if (i % 4 == 0 || i % 4 == 3) {
            r2 *= 0.75;
        }
#line 399
        xy [i * 2 + 0] = rx + c * r2;
        xy [i * 2 + 1] = ry + s * r2;
    }
#line 401
    land_filled_polygon(34, xy);
}
static void draw_jump_controls(void) {
    All * a = global_a;
    if (a->dpad > 3) {
#line 405
        return ;
    }
    land_color(0.5, 0.4, 0, 0.5);
    float w = land_display_width();
    float h = land_display_height();
    float rr = w / 8 * 0.8;
    if (a->dpad == 2 || a->dpad == 3) {
        rr *= 1.5;
    }
#line 413
    float rx = w - rr;
    float ry = h - rr;
    if (a->dpad == 1 || a->dpad == 3) {
        rx = rr;
    }
#line 417
    rr *= 0.6;
    land_filled_circle(rx - rr, ry - rr, rx + rr, ry + rr);
}
static void draw_pause_controls(void) {
    land_color(0.5, 0.4, 0, 0.5);
    float w = land_display_width();
    float rr = w / 8 * 0.8;
#line 425
    if (global_a->show_map) {
#line 427
        land_filled_triangle(w - rr / 8, rr / 2, w - rr, rr, w - rr, 0);
#line 430
        land_filled_triangle(w - rr, w / 8 + rr / 2, w - rr / 8, w / 8, w - rr / 8, w / 8 + rr);
    }
#line 430
    else {
#line 433
        land_filled_rectangle(w - rr, rr / 8, w - rr + rr * 3 / 8, rr * 7 / 8);
#line 435
        land_filled_rectangle(w - rr + rr * 4 / 8, rr / 8, w - rr + rr * 7 / 8, rr * 7 / 8);
    }
}
#line 437
void render(Game * g, float w, float h) {
    All * a = global_a;
    float fh = land_font_height(a->medium);
    //float z = g.viewport->zoom
#line 442
    land_clear_depth(1);
#line 444
    if (game->sequence) {
        a->tint = intro_tint;
        land_clear(intro_back.r, intro_back.g, intro_back.b, intro_back.a);
    }
#line 446
    else {
#line 448
        a->tint.a = 0;
#line 450
        land_clear(r.background_color.r, r.background_color.g, r.background_color.b, r.background_color.a);
    }
    if (a->show_ad) {
        land_stream_volume(r.music, 0);
        render_ad_screen();
#line 454
        return ;
    }
#line 457
    if (a->overview) {
        overview_render(game->overview);
    }
#line 459
    else if (! a->show_map) {
        render_blocks(g->blocks, g->viewport);
#line 462
        if (game->sequence && ! a->render_screenshot) {
            intro_postprocess();
        }
    }
#line 465
    land_reset_transform();
    land_render_state(LAND_DEPTH_TEST, 0);
#line 468
    if (! game->sequence && ! a->render_screenshot) {
#line 470
        if (! a->show_map && global_use_touch_input) {
            draw_move_controls();
            draw_jump_controls();
        }
#line 473
        if (global_use_touch_input || a->show_map) {
            draw_pause_controls();
        }
        if (game->menu_on) {
            menu_draw(game->menu);
        }
    }
#line 479
    land_color(0, 0, 0, 1);
    land_font_set(a->medium);
#line 482
    land_push_transform();
    land_scale(w / 960.0, w / 960.0);
#line 485
    if (a->overview) {
        land_color(0, 0, 0, 1);
        land_text_pos(0, 0);
        land_print("%d", g->overview->selected);
    }
    if (a->show_map) {
        map_render();
    }
    if (! a->render_screenshot && ! a->overview) {
#line 495
        float v [8];
        float o = 72;
        float m = 480;
        Viewport * vp = game->viewport;
#line 500
        if (a->editor) {
            project(vp, o - m, 0, o - m, v + 0, v + 1);
            project(vp, o - m, 0, o + m, v + 2, v + 3);
            project(vp, o + m, 0, o + m, v + 4, v + 5);
            project(vp, o + m, 0, o - m, v + 6, v + 7);
            land_color(.5, .5, .5, 1);
            land_polygon(4, v);
        }
        land_color(0, 0, 0, 1);
        land_text_pos(0, 0);
        land_print("%s", g->title);
        if (a->editor) {
            land_print("%d", g->level);
        }
        if (g->ticks < 300) {
#line 516
            land_text_pos(960 * 3 / 4, fh);
            land_print_center("%s", "Yellow and Dangerous");
            land_print_center("%s", "by Allefant");
        }
        if (! a->show_map && (g->ticks > 600 || a->editor)) {
            float y = h / (w / 960) - 3 * fh;
            land_text_pos(0, y);
            land_print_wordwrap(w, h, "%s", g->hint);
        }
        if (g->record->is_recording) {
            land_color(1, 0, 0, 1);
            if (! g->record->wait_on_level || ((g->ticks / 30) & 1)) {
                land_filled_circle(940, 0, 960, 20);
            }
        }
#line 529
        if (g->record->is_replaying) {
            land_color(0, 0, 1, 1);
            if (! g->record->wait_on_level || ((g->ticks / 30) & 1)) {
                land_filled_circle(940, 0, 960, 20);
            }
        }
    }
#line 534
    land_pop_transform();
}
void render_block_scaled(Block * self, Viewport * viewport, double scaled) {
    All * a = global_a;
    BlockType * bt = self->block_type;
    float x, y;
#line 544
    project(viewport, self->x + self->xs / 2, self->y + self->ys / 2, self->z + self->zs / 2, & x, & y);
    //x += bt->x
    //y += bt->y
#line 548
    bool hide = bt->invisible;
    if (bt == Render_Waypoint) {
        if (! a->editor) {
            hide = 1;
        }
    }
#line 553
    if (self->block_type->bitmaps && ! hide) {
        float cr = 1;
        float cg = 1;
        float cb = 1;
        float ca = 1;
        float scale = 24;
        float height = floor(self->y / scale + 4);
        if (bt->transparent) {
            height = 0;
        }
#line 562
        if (height >= 0) {
            cb -= height / 64.0;
            cg -= height / 128.0;
        }
#line 564
        else {
#line 566
            cb += height / 64;
            cr += height / 64;
        }
#line 568
        if (a->tint.a) {
            cr = a->tint.r;
            cg = a->tint.g;
            cb = a->tint.b;
            ca = a->tint.a;
        }
        LandImage * frame = land_array_get_nth(bt->bitmaps, self->frame);
        land_image_load_on_demand(frame);
        //x -= land_image_width(frame) / 4
        //y -= land_image_height(frame) / 4
#line 579
        land_image_draw_scaled_tinted(frame, x, y, scaled, scaled, cr, cg, cb, ca);
    }
    bool show_bounds = debug_bounding_boxes || self == editor->picked;
    bool show_misaligned = 0;
    bool show_ground = self == editor->picked;
#line 585
    if (a->editor) {
        float s = 24;
#line 588
        if (self->y < - s * 6) {
            show_ground = 1;
            show_bounds = 1;
        }
        float ix = self->x / s;
        float iy = self->y / s;
        float iz = self->z / s;
        int xi = floor(ix);
        int yi = floor(iy);
        int zi = floor(iz);
        if (xi != ix || yi != iy || zi != iz) {
            show_bounds = 1;
            show_misaligned = 1;
        }
    }
#line 602
    if (show_bounds) {
        float x2 = self->x + self->xs;
        float y2 = self->y + self->ys;
        float z2 = self->z + self->zs;
#line 607
        float v [22];
        project(viewport, self->x, y2, self->z, v + 0, v + 1);
        project(viewport, self->x, y2, z2, v + 2, v + 3);
        project(viewport, x2, y2, z2, v + 4, v + 5);
        project(viewport, x2, y2, self->z, v + 6, v + 7);
        project(viewport, self->x, self->y, z2, v + 8, v + 9);
        project(viewport, x2, self->y, z2, v + 10, v + 11);
        project(viewport, x2, self->y, self->z, v + 12, v + 13);
        //
        //      0
        //    /   .
        //  1       3
        //  | \   / |
        //  4   2   6
        //    \ | /
        //      5
#line 625
        if (show_misaligned) {
            land_color(0.75, 0, 0.75, 1);
            land_line(v [0], v [1], v [4], v [5]);
            land_line(v [2], v [3], v [6], v [7]);
        }
#line 628
        else {
#line 630
            land_color(0, 0, 0, 1);
        }
        land_line(v [0], v [1], v [2], v [3]);
        land_line(v [2], v [3], v [8], v [9]);
        land_line(v [8], v [9], v [10], v [11]);
        land_line(v [10], v [11], v [12], v [13]);
        land_line(v [12], v [13], v [6], v [7]);
        land_line(v [6], v [7], v [0], v [1]);
#line 639
        if (show_ground) {
            project(viewport, self->x, 0, self->z, v + 14, v + 15);
            project(viewport, self->x, 0, z2, v + 16, v + 17);
            project(viewport, x2, 0, z2, v + 18, v + 19);
            project(viewport, x2, 0, self->z, v + 20, v + 21);
            land_color(1, 0, 0, 1);
            land_line(v [14], v [15], v [16], v [17]);
            land_line(v [16], v [17], v [18], v [19]);
            land_line(v [18], v [19], v [20], v [21]);
            land_line(v [20], v [21], v [14], v [15]);
        }
    }
}
#line 650
void render_block(Block * self, Viewport * viewport) {
    render_block_scaled(self, viewport, 0.5);
}
void render_blocks(Blocks * blocks, Viewport * viewport) {
    // Each block has a cache of other blocks which are drawn earlier but also
    // need to appear in front of the block. For static blocks this cache is
    // built only the first time they are drawn. Since all static blocks are
    // drawn before any dynamic blocks, that cache cannot possibly change after
    // all.
    // For dynamic blocks the cache has to be rebuilt whenever any of them moves
    // however.
#line 663
    float z = viewport->zoom;
    land_reset_transform();
    land_scale(z, z);
#line 667
    int n1 = land_array_count(blocks->fixed);
    int n2 = land_array_count(blocks->dynamic);
    int n3 = land_array_count(blocks->transparent);
    for (int i = 0; i < n1 + n2 + n3; i += 1) {
        Block * b;
        if (i < n1) {
            b = land_array_get_nth(blocks->fixed, i);
        }
#line 674
        else if (i < n1 + n2) {
            b = land_array_get_nth(blocks->dynamic, i - n1);
        }
#line 675
        else {
#line 677
            b = land_array_get_nth(blocks->transparent, i - n1 - n2);
        }
        BlockType * bt = b->block_type;
#line 681
        bool need_mask = 0;
        // Need to rebuild the cache for this block?
#line 686
        if ((! bt->dynamic && blocks->rebuild_static_cache) || (bt->dynamic && blocks->rebuild_dynamic_cache) || (bt->transparent && blocks->rebuild_dynamic_cache)) {
#line 688
            land_array_clear(b->cache);
#line 690
            int n = n1;
            if (bt->dynamic || bt->transparent) {
                n += n2;
            }
            for (int j = 0; j < n; j += 1) {
                Block * already;
                if (j < n1) {
                    already = land_array_get_nth(blocks->fixed, j);
                }
#line 697
                else {
#line 699
                    already = land_array_get_nth(blocks->dynamic, j - n1);
                }
#line 700
                if (debug_no_mask) {
#line 700
                    break;
                }
#line 701
                if (already == b) {
#line 701
                    break;
                }
#line 702
                if (block_sort_order(already, b, viewport) == 1) {
                    land_array_add(b->cache, already);
                }
            }
        }
#line 705
        {
#line 705
            LandArrayIterator __iter0__ = LandArrayIterator_first(b->cache);
#line 705
            for (Block * already = LandArrayIterator_item(b->cache, &__iter0__); LandArrayIterator_next(b->cache, &__iter0__); already = LandArrayIterator_item(b->cache, &__iter0__)) {
                if (! debug_no_mask && ! need_mask) {
                    need_mask = 1;
                    // Unconditionally write into depth buffer only (to create
                    // mask). The mask will have all blocks which have been
                    // drawn already but are in front (and so should not be
                    // overdrawn).
#line 714
                    land_render_state(LAND_DEPTH_TEST, 1);
                    land_render_state(LAND_DEPTH_FUNCTION, LAND_ALWAYS);
                    land_render_state(LAND_WRITE_MASK, LAND_DEPTH_MASK);
#line 718
                    float x1, y1, x2, y2;
                    block_get_bounding_rect(b, viewport, & x1, & y1, & x2, & y2);
                    x1 -= 30;
                    y1 -= 30;
                    x2 += 60;
                    y2 += 60;
#line 725
                    land_clip((int)(x1 * z), (int)(y1 * z), (int)(x2 * z) + 1, (int)(y2 * z) + 1);
                }
                render_block(already, viewport);
            }
        }
#line 729
        if (! debug_no_mask && need_mask) {
            // Write only color (no depth), but only where there is no mask.
            land_render_state(LAND_DEPTH_FUNCTION, LAND_LESS);
            land_render_state(LAND_WRITE_MASK, LAND_RGBA_MASK);
        }
        //x1, y1, x2, y2 = b.get_bounding_rect(viewport)
#line 736
        render_block(b, viewport);
        //if not debug->no_mask and need_mask:
        //    render_block(b, viewport)
        //c = al_map_rgb_f(1, 0, 0)
        //al_draw_line(x1 + 2, y1 + 2, x2 - 2, y1 + 2, c, 1)
        //al_draw_line(x1 + 2, y1 + 2, x1 + 2, y2 - 2, c, 1)
#line 744
        if (! debug_no_mask && need_mask) {
            // Restore everything to how it was before this block was drawn.
            land_render_state(LAND_WRITE_MASK, LAND_DEPTH_MASK | LAND_RGBA_MASK);
            land_clear_depth(1);
#line 749
            land_render_state(LAND_DEPTH_TEST, 0);
            land_unclip();
        }
    }
    //for Block *b in LandArray *blocks->transparent:
    //    render_block(b, viewport)
    blocks->rebuild_static_cache = 0;
    blocks->rebuild_dynamic_cache = 0;
}
/* This file was generated by scramble.py. */
