/* This file was generated by scramble.py. */
#line 1 "src/save.py"
#ifndef _SAVE_
#define _SAVE_
typedef struct SaveInfo SaveInfo;
#line 1
#include "common.h"
#line 27
struct SaveInfo {
    bool saved;
    bool exits [4];
    int n;
    float * xy;
};
#include "block.h"
#include "game.h"
#include "editor.h"
#line 43
void save_info(void);
#line 63
void load_info(void);
#line 119
void save_get_name(char const * base, int level, char const * suffix, char * out);
#line 125
void save_level(bool editing);
#line 185
void save_check(int level);
#line 240
void load_level(bool editing);
#line 325
void save_load_from_offset(LandBuffer * f, int ox, int oy, int oz, bool editing);
#line 371
void save_reset_room(int i);
#line 379
void save_new(void);
#line 390
bool save_is_saved(int i);
#line 393
int save_get_level_n(int i);
#line 396
float* save_get_level_xy(int i);
#endif
/* This file was generated by scramble.py. */
