/* This file was generated by scramble.py. */
#line 1 "src/testtube.py"
#ifndef _TESTTUBE_
#define _TESTTUBE_
#line 1
#include "common.h"
#include "block.h"
#line 2
#include "render.h"
#line 4
void testtube_touch(Block * super, Block * c, float dx, float dy, float dz);
#line 14
void testtube_tick(Block * super);
#endif
/* This file was generated by scramble.py. */
