/* This file was generated by scramble.py. */
#line 1 "src/testtube.py"
#include "testtube.h"
#line 4
void testtube_touch(Block * super, Block * c, float dx, float dy, float dz) {
    if (dy < 0 && super->dy < - 2) {
        // change to yellow stain
#line 8
        if (super->frame == 5 && c->block_type == Render_Floor) {
            c->frame = 1;
        }
        super->y = - 9000;
        sound(Render_glass, 1);
    }
}
#line 14
void testtube_tick(Block * super) {
    super->dy += land_rnd(0, 0.5);
    block_tick(super);
}
/* This file was generated by scramble.py. */
