/* This file was generated by scramble.py. */
#line 1 "src/test.py"
#ifndef _TEST_
#define _TEST_
#line 1
#include "game.h"
#line 5
bool test(void);
#line 50
bool test_level(int level, int x, int y, int z, int * tick);
#endif
/* This file was generated by scramble.py. */
