/* This file was generated by scramble.py. */
#line 1 "src/title.py"
#include "title.h"
#line 17
static str menu_text = "\n"
    "Play\n"
    "Reset Room\n"
    "New Game\n"
    "    -Are you sure?\n"
    "    -\n"
    "    Delete savegame!\n"
    "    Continue Playing\n"
    "Settings\n"
    "    Controls\n"
    "        Gamepad\n"
    "        Left/Right\n"
    "            -Configure H axis\n"
    "            Left\n"
    "            Right\n"
    "            Done\n"
    "        Up/Down\n"
    "            -Configure V axis\n"
    "            Up\n"
    "            Down\n"
    "            Done\n"
    "        Jump/Pull\n"
    "            -Configure buttons\n"
    "            Jump/Pull\n"
    "            Menu\n"
    "            Done\n"
    "        Back\n"
    "    Audio\n"
    "        -Volume\n"
    "        Music\n"
    "        Sound\n"
    "        Back\n"
    "    Video\n"
    "        Fullscreen|Back to Windowed\n"
    "        Back\n"
    "    Back\n"
    "";
#line 55
static MenuScreen * menu;
static MenuScreen * menu_main;
static Block * block1;
static Block * block2;
static int moment;
static bool selected_blocking;
static bool finding_input;
static int finding_control;
static int finding_progress;
#line 65
static float ppx, ppy, ppw, pph;
static void _find_control(int c);
static int _indentation(str x);
static void drawvol(int v, float x, float y);
static int volget(float mx);
static void music_volume(int i);
static void sound_volume(int i);
static void draw_title_animation(void);
#line 67
MenuScreen* menu_screen_new(void) {
    MenuScreen * self;
#line 68
    land_alloc(self);
    self->items = land_array_new();
    return self;
}
MenuScreenItem* menu_screen_add(MenuScreen * self, str text) {
    MenuScreenItem * item;
#line 73
    land_alloc(item);
    if (land_starts_with(text, "-")) {
        item->disabled = 1;
        text++;
    }
#line 77
    if (land_contains(text, "|")) {
        item->alternates = land_split(text, "|");
        text = land_array_get_nth(item->alternates, 0);
    }
#line 80
    if (land_equals(text, "Controls")) {
        if (global_use_touch_input) {
            text = "Touch";
        }
    }
#line 84
    item->text = text;
    land_array_add(self->items, item);
    return item;
}
bool menu_is(str x) {
    return land_equals(menu->name, x);
}
MenuScreenItem* menu_item_get(void) {
    if (menu->selected >= land_array_count(menu->items)) {
#line 92
        return NULL;
    }
#line 93
    return land_array_get_nth(menu->items, menu->selected);
}
bool menu_item_is(str x) {
    MenuScreenItem * item = menu_item_get();
    if (! item) {
        return 0;
    }
#line 99
    return land_equals(item->text, x);
}
void menu_screen_back(void) {
    if (menu_is("New Game")) {
        main_switch_to_game();
    }
#line 104
    else if (menu_is("Controls")) {
        menu_goto("Settings");
    }
#line 106
    else if (menu_is("Main")) {
        main_switch_to_game();
    }
#line 107
    else {
#line 109
        menu_goto("Main");
        save_info();
    }
}
#line 112
void menu_goto(str x) {
    if (land_equals(x, "Main")) {
        menu = menu_main;
#line 114
        return ;
    }
    {
#line 116
        LandArrayIterator __iter0__ = LandArrayIterator_first(menu_main->items);
#line 116
        for (MenuScreenItem * item = LandArrayIterator_item(menu_main->items, &__iter0__); LandArrayIterator_next(menu_main->items, &__iter0__); item = LandArrayIterator_item(menu_main->items, &__iter0__)) {
            if (land_equals(item->text, x)) {
                menu = item->target;
#line 118
                return ;
            }
        }
    }
#line 120
    {
#line 120
        LandArrayIterator __iter0__ = LandArrayIterator_first(menu->items);
#line 120
        for (MenuScreenItem * item = LandArrayIterator_item(menu->items, &__iter0__); LandArrayIterator_next(menu->items, &__iter0__); item = LandArrayIterator_item(menu->items, &__iter0__)) {
            if (land_equals(item->text, x)) {
                menu = item->target;
#line 122
                return ;
            }
        }
    }
#line 124
    print("Cannot goto menu %s", x);
}
void menu_goup(void) {
    menu = menu->parent;
}
void menu_select_next(int d) {
    int n = land_array_count(menu->items);
    for (int i = 0; i < n; i += 1) {
        menu->selected += d;
        if (menu->selected == - 1) {
#line 133
            menu->selected += n;
        }
#line 134
        if (menu->selected == n) {
#line 134
            menu->selected = 0;
        }
#line 135
        MenuScreenItem * msi = land_array_get_nth(menu->items, menu->selected);
        if (msi->disabled) {
#line 136
            continue;
        }
#line 137
        break;
    }
}
#line 139
void menu_sideways(int d) {
    if (menu_is("Audio")) {
        if (menu_item_is("Music")) {
            music_volume(global_a->music + d);
        }
#line 143
        if (menu_item_is("Sound")) {
            sound_volume(global_a->sound + d);
        }
    }
}
#line 146
void menu_select_position(int p) {
    menu->selected = p;
}
static void _find_control(int c) {
    finding_input = 1;
    finding_control = c;
    finding_progress = 0;
}
void menu_click(float x) {
    All * a = global_a;
#line 157
    MenuScreenItem * item = menu_item_get();
    if (item) {
        if (item->target) {
            if (menu_is("Controls")) {
                menu = item->target;
                menu_select_position(1);
                menu_click(0);
#line 163
                return ;
            }
#line 166
            if (menu_is("Main")) {
                if (menu_item_is("New Game")) {
                    a->code = 0;
                    a->godmode = 0;
                }
            }
#line 170
            menu = item->target;
#line 170
            return ;
        }
    }
#line 172
    if (menu_is("Left/Right")) {
        if (menu_item_is("Left")) {
#line 173
            _find_control(ControlLeft);
        }
#line 174
        if (menu_item_is("Right")) {
#line 174
            _find_control(ControlRight);
        }
#line 175
        if (menu_item_is("Done")) {
#line 175
            menu_goup();
        }
    }
#line 176
    else if (menu_is("Up/Down")) {
        if (menu_item_is("Up")) {
#line 177
            _find_control(ControlUp);
        }
#line 178
        if (menu_item_is("Down")) {
#line 178
            _find_control(ControlDown);
        }
#line 179
        if (menu_item_is("Done")) {
#line 179
            menu_goup();
        }
    }
#line 180
    else if (menu_is("Jump/Pull")) {
        if (menu_item_is("Jump/Pull")) {
#line 181
            _find_control(ControlJump);
        }
#line 182
        if (menu_item_is("Menu")) {
#line 182
            _find_control(ControlMenu);
        }
#line 183
        if (menu_item_is("Done")) {
#line 183
            menu_goup();
        }
    }
#line 184
    else if (menu_is("Settings")) {
        if (menu_item_is("Touch")) {
            a->dpad++;
            if (a->dpad == 6) {
                a->dpad = 0;
            }
        }
    }
#line 189
    else if (menu_is("Audio")) {
        if (menu_item_is("Music")) {
            music_volume(volget(x));
        }
#line 192
        else if (menu_item_is("Sound")) {
            sound_volume(volget(x));
        }
    }
#line 194
    else if (menu_is("Video")) {
        if (menu_item_is("Fullscreen")) {
            land_display_toggle_fullscreen();
            a->fullscreen = (land_display_flags() & LAND_FULLSCREEN) != 0;
            item->choice = a->fullscreen ? 1 : 0;
        }
    }
#line 199
    else if (menu_is("New Game")) {
        if (menu_item_is("Delete savegame!")) {
            // start new game
            save_new();
            main_switch_to_game();
        }
#line 204
        else if (menu_item_is("Continue Playing")) {
            main_switch_to_game();
        }
    }
#line 206
    else if (menu_is("Controls")) {
#line 206
        ;
    }
    else if (menu_is("Main")) {
        if (menu_item_is("Play")) {
            if (global_can_enable_editor && volget(x) > 0) {
                a->editor_enabled = 1;
                a->editor = 1;
            }
#line 212
            else {
#line 214
                a->editor_enabled = 0;
            }
            // load saved game
            main_switch_to_game();
        }
#line 218
        else if (menu_item_is("Reset Room")) {
            // reset the current room
            save_reset_room(game->level);
            main_switch_to_game();
            if (game->player) {
                player_find_entrance(& game->player->super);
            }
        }
    }
#line 225
    if (menu_item_is("Back")) {
        menu_screen_back();
    }
}
#line 228
static int _indentation(str x) {
    int i = 0;
    while (x [i] == ' ') {
        i++;
    }
#line 232
    return i;
}
void title_init(void) {
    MenuScreen * menus [100];
    menus [0] = menu_main = menu_screen_new();
    menu_main->name = "Main";
    LandArray * rows = land_split_lines(menu_text);
    int prev_nested = 0;
    MenuScreenItem * prev_item = NULL;
    MenuScreen * prev_menu = NULL;
    {
#line 242
        LandArrayIterator __iter0__ = LandArrayIterator_first(rows);
#line 242
        for (str row_raw = LandArrayIterator_item(rows, &__iter0__); LandArrayIterator_next(rows, &__iter0__); row_raw = LandArrayIterator_item(rows, &__iter0__)) {
            int nested = _indentation(row_raw);
            if (nested > prev_nested) {
                menus [nested] = menu_screen_new();
                menus [nested]->name = prev_item->text;
                if (! land_equals(prev_item->text, "Touch")) {
                    prev_item->target = menus [nested];
                }
#line 249
                menus [nested]->parent = prev_menu;
            }
#line 250
            prev_nested = nested;
            prev_menu = menus [nested];
            char * row = land_strdup(row_raw);
            land_strip(& row);
            if (! row [0]) {
#line 254
                continue;
            }
#line 255
            prev_item = menu_screen_add(menus [nested], row);
        }
    }
#line 257
    land_array_destroy_with_strings(rows);
#line 259
    menu = menu_main;
}
int get_line(float y) {
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
#line 267
    float by = (h - 64 * 5) / 2;
    y /= s;
    y -= by;
    y /= 64;
#line 272
    return y;
}
// 0 = main, 1 = settings
void title_com(int com) {
    if (com == 1) {
        menu_goto("Settings");
    }
#line 277
    else {
#line 279
        menu_goto("Main");
    }
}
#line 281
void title_tick(void) {
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
#line 287
    All * a = global_a;
#line 289
    if (finding_input) {
        int status = config_joystick_control(finding_control, finding_progress);
        if (status == FoundButton) {
            finding_input = 0;
        }
#line 293
        if (status == FoundAxis) {
            finding_progress++;
        }
#line 295
        if (status == FoundNothing) {
            // wait until they stop using the input
#line 296
            if (finding_progress >= 10) {
                finding_input = 0;
            }
        }
#line 298
        if (! finding_input) {
            menu_select_next(1);
            menu_click(0) /* either next control or done */;
        }
#line 300
        return ;
    }
#line 303
    if (land_key_pressed(LandKeyBack) || controls.pressed [ControlMenu]) {
        menu_screen_back();
    }
    if (selected_blocking) {
        if (! a->up && ! a->down && ! a->left && ! a->right) {
            selected_blocking = 0;
        }
    }
#line 309
    else if (a->up || a->down) {
        menu_select_next(a->up ? - 1 : 1);
        selected_blocking = 1;
    }
#line 312
    else if (a->left || a->right) {
        menu_sideways(a->left ? - 1 : 1);
        selected_blocking = 1;
    }
    for (int ti = 0; ti < 12; ti += 1) {
        bool click = 0;
        int i = 0;
        int i2 = 0;
        float x = 0;
        if (ti < 11) {
            if (land_touch_down(ti) && land_touch_delta(ti)) {
                click = 1;
            }
#line 324
            i2 = get_line(land_touch_y(ti));
            i = i2;
            if (i > 0) {
#line 326
                i--;
            }
#line 327
            x = land_touch_x(ti);
#line 329
            if (click) {
                float y = land_touch_y(ti);
                land_log_message("%f %f %f %f %f %f", x, y, ppx, ppy, ppw, pph);
                if (x > ppx && x < ppx + ppw && y > ppy && y < ppy + pph) {
                    open_link("http://yellowdanger.com/privacy_policy.html");
#line 333
                    return ;
                }
            }
        }
#line 333
        else {
#line 336
            if (controls.pressed [ControlJump]) {
                i = menu->selected;
                click = 1;
            }
        }
#line 340
        if (click) {
            if (i2 == 1) {
                if (menu_is("New Game")) {
                    a->code++;
                    if (a->code == 7) {
                        sound(Render_glass, 1);
                        a->godmode = 1;
                    }
                }
            }
#line 346
            else {
#line 348
                menu_select_position(i);
                menu_click(x);
            }
        }
    }
}
#line 352
static int volx = 0;
static void drawvol(int v, float x, float y) {
    LandColor c = land_color_get();
    y += 16;
    float s = 48;
    for (int i = 0; i < 7; i += 1) {
        float ix = x + i * s;
        float iy = y;
        land_color(1, 1, 1, 1);
        if (i <= v) {
            if (v == 0) {
                land_color(0, 0, 0, 1);
            }
#line 364
            land_filled_rectangle(ix, iy, ix + s * 0.8, iy + s);
        }
#line 364
        else {
#line 366
            float cx = ix + s * 0.4;
            float cy = iy + s * 0.5;
            land_filled_circle(cx - 4, cy - 4, cx + 4, cy + 4);
        }
    }
#line 369
    land_color_set(c);
}
void menu_screen_draw(void) {
    All * a = global_a;
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
    land_font_set(a->big);
    float th = land_line_height();
    float yw = land_text_get_width("Yellow ");
    land_color(.9, .9, 0.7, 1);
    float tx = (960 - land_text_get_width("Yellow and Dangerous")) / 2;
#line 383
    int it = 0;
    {
#line 384
        LandArrayIterator __iter0__ = LandArrayIterator_first(menu->items);
#line 384
        for (MenuScreenItem * item = LandArrayIterator_item(menu->items, &__iter0__); LandArrayIterator_next(menu->items, &__iter0__); item = LandArrayIterator_item(menu->items, &__iter0__)) {
            int it2 = it;
            if (it2 > 0) {
                it2++;
            }
#line 388
            float y = (h - 64 * 5) / 2 + it2 * 64 + (32 - th) / 2;
            float x = tx;
            bool draw = 1;
            land_text_pos(x + yw, y);
            land_color(0.5, 0, 0, 1);
            if (it == menu->selected) {
                land_color(0.9, 0.1, 0, 1);
                if (finding_input) {
                    if ((land_get_ticks() / 5) % 2 == 0) {
                        land_color(1, 1, 1, 1);
                    }
                }
            }
#line 397
            else {
#line 399
                land_color(0.5, 0, 0, 1);
            }
            if (menu_is("Settings")) {
                if (it == 0) {
                    if (global_use_touch_input) {
                        if (a->dpad == 0) {
#line 404
                            land_print("DPad left");
                        }
#line 405
                        if (a->dpad == 1) {
#line 405
                            land_print("DPad right");
                        }
#line 406
                        if (a->dpad == 2) {
#line 406
                            land_print("DPad left big");
                        }
#line 407
                        if (a->dpad == 3) {
#line 407
                            land_print("DPad right big");
                        }
#line 408
                        if (a->dpad == 4) {
#line 408
                            land_print("double click swipe");
                        }
#line 409
                        if (a->dpad == 5) {
#line 409
                            land_print("two finger swipe");
                        }
#line 410
                        draw = 0;
                    }
                }
            }
#line 411
            else if (menu_is("Audio")) {
                if (it == 1) {
                    drawvol(a->music, volx, y);
                }
#line 414
                else if (it == 2) {
                    drawvol(a->sound, volx, y);
                }
            }
#line 416
            else if (menu_is("New Game")) {
                if (it == 0) {
                    land_color(1, 0.75, 0.75, 1);
                }
#line 419
                else if (it == 2) {
                    if (it == menu->selected) {
                        land_color(1, 0.4, 0.4, 1);
                    }
                }
#line 422
                else if (it == 3) {
                    if (it == menu->selected) {
                        land_color(0, 0.5, 0, 1);
                    }
                }
            }
#line 426
            if (draw) {
                if (item->alternates) {
#line 429
                    land_print(land_array_get_nth(item->alternates, item->choice));
                }
#line 429
                else {
#line 431
                    land_print(item->text);
                }
            }
#line 433
            if (menu_is("Main")) {
                if (it == 0) {
                    if (global_can_enable_editor) {
                        land_text_pos(volx + 48, y);
                        land_print("Edit");
                    }
                }
            }
#line 439
            int control = ControlNone;
            if (menu_is("Left/Right")) {
                if (it == 1) {
#line 441
                    control = ControlLeft;
                }
#line 442
                if (it == 2) {
#line 442
                    control = ControlRight;
                }
            }
#line 443
            if (menu_is("Up/Down")) {
                if (it == 1) {
#line 444
                    control = ControlUp;
                }
#line 445
                if (it == 2) {
#line 445
                    control = ControlDown;
                }
            }
#line 446
            if (menu_is("Jump/Pull")) {
                if (it == 1) {
#line 447
                    control = ControlJump;
                }
#line 448
                if (it == 2) {
#line 448
                    control = ControlMenu;
                }
            }
#line 449
            if (menu_is("Controls")) {
                if (it == 1) {
#line 450
                    control = ControlLeft;
                }
#line 451
                if (it == 2) {
#line 451
                    control = ControlUp;
                }
#line 452
                if (it == 3) {
#line 452
                    control = ControlJump;
                }
            }
#line 454
            if (control) {
                land_font_set(a->medium);
                land_text_pos(volx + 68, y);
                land_color(0, 0, 0, 0.33);
                land_print(control_name(control));
                land_font_set(a->big);
            }
            it++;
        }
    }
}
#line 463
static int volget(float mx) {
    float w = land_display_width();
    double s = w / 960;
    float sx = 48;
    mx /= s;
    int i = (mx - volx) / sx;
    return i;
}
static void music_volume(int i) {
    if (i < 0) {
#line 472
        i = 0;
    }
#line 473
    if (i > 6) {
#line 473
        i = 6;
    }
#line 474
    global_a->music = i;
    song_volume();
}
static void sound_volume(int i) {
    if (i < 0) {
#line 478
        i = 0;
    }
#line 479
    if (i > 6) {
#line 479
        i = 6;
    }
#line 480
    global_a->sound = i;
    sound(Render_on, 1);
}
float align(float x, float s) {
    return floor(x * s) / s;
}
void title_render(void) {
    All * a = global_a;
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
    land_clear(1, 1, 1, 1);
#line 494
    land_reset_transform();
    land_scale(s, s);
#line 497
    land_font_set(a->big);
    float th = land_line_height();
    float yw = land_text_get_width("Yellow ");
#line 501
    land_color(.9, .9, 0.7, 1);
    float tx = (960 - land_text_get_width("Yellow and Dangerous")) / 2;
    land_filled_rectangle(tx + yw, 0, 960, h);
#line 505
    if (menu_is("Settings")) {
        land_font_set(a->medium);
        land_color(0.5, 0, 0, 1);
        float nh = land_line_height();
        float y = (h - 64 * 5) / 2 + (32 - th) / 2;
        float x = tx;
        land_text_pos(x + yw, y - nh * 2);
        if (global_use_touch_input) {
            if (a->dpad == 5) {
                land_print("Jump: touch second finger");
                land_print("Pull/Lift: two finger swipe");
            }
#line 516
            else if (a->dpad == 4) {
                land_print("Jump: Move then double tap");
                land_print("Pull/Lift: Double tap then move");
            }
#line 518
            else {
#line 520
                land_print("Jump: Hold move then jump");
                land_print("Pull/Lift: Hold jump then move");
            }
        }
#line 521
        else {
#line 523
            land_print("Jump: Press button while moving");
            land_print("Pull/Lift: Press button first then move");
        }
#line 525
        land_font_set(a->big);
    }
    volx = tx + yw + 6 * 32;
#line 529
    if (1) {
        int i = 1;
        float y = (h - 64 * 5) / 2 + i * 64 + (32 - th) / 2;
        float x = tx;
        land_color(1, 0.9, 0, 1);
        land_text_pos(x, y);
        land_write("Yellow ");
        land_color(1, 1, 1, 1);
        if ((land_get_ticks() / 60) % 14 >= 7) {
            if (land_get_ticks() % 8 >= 4) {
                land_color(1, 1, 0, 1);
            }
        }
#line 540
        land_print("and Dangerous");
    }
    menu_screen_draw();
#line 544
    land_font_set(a->font);
    land_color(0, 0, 0, 1);
#line 547
    if (! block1) {
        block1 = block_new(game->blocks, 120, 0, 720, Render_Gremlin);
    }
#line 549
    if (! block2) {
        block2 = block_new(game->blocks, - 660, 0, - 60, Render_Allefant);
    }
    moment++;
    if (moment > 4) {
        // wait a moment so Android gets a moment to recover and
        // won't crash :P
        draw_title_animation();
    }
    a->tint.a = 0;
#line 560
    land_font_set(a->font);
    land_text_pos(w / s, h - land_line_height() * 6);
    int t = a->time / 60;
    int f = 0;
    for (int i = 0; i < 8; i += 1) {
        if (game->flower [i]) {
            f++;
        }
    }
#line 567
    int tt = 0;
    for (int i = 0; i < 8; i += 1) {
        if (game->test_tube [i]) {
            tt++;
        }
    }
#line 571
    land_print_right("Flowers picked: %d/7", f);
    land_print_right("Test tubes: %d/7", tt);
    land_print_right("Car keys found: %s", game->key ? "yes" : "no");
    land_print_right("Died %d time%s.", game->deaths, game->deaths != 1 ? "s" : "");
#line 576
    land_print_right("Playtime on this savegame: %02d:%02d:%02d", t / 3600, (t / 60) % 60, t % 60);
    land_print_right("Version %s", VERSION);
#line 579
    land_font_set(a->medium);
    land_color(.3, 0.3, 1, 1);
    land_text_pos(4, h - 4 - land_line_height());
    land_print("Privacy Policy");
    ppx = land_text_x() * s;
    ppy = land_text_y() * s;
    ppw = land_text_width() * s;
    pph = land_text_height() * s;
}
static void draw_title_animation(void) {
    All * a = global_a;
    float speed = 60 * 7 / 2.0;
    for (int i = 0; i < 7; i += 1) {
        float ang = (land_get_ticks() + i * speed / 7) * 2 * pi / speed;
        block1->y = 60 * fabs(sin(ang * 3.5));
        block1->x = 0 + cos(ang) * 120;
        block1->z = 600 + sin(ang) * 120;
        block1->frame = ((land_get_ticks() / 30 + i) % 4) * 4;
        if (((land_get_ticks() / 60) % 14 >= 7) && i == 0) {
            a->tint = land_color_hsv((land_get_ticks() * 4) % 360, .25, 1);
            a->tint.a = 0.5;
            a->tint.r *= a->tint.a;
            a->tint.g *= a->tint.a;
            a->tint.b *= a->tint.a;
        }
#line 602
        else {
#line 604
            a->tint = land_color_premul(1, 1, 1, .2);
        }
#line 605
        if (! blocktype_preload(block1->block_type)) {
            render_block(block1, game->viewport);
        }
    }
#line 608
    a->tint = land_color_premul(1, 1, 1, .2);
#line 610
    block2->frame = 8 + ((16 * land_get_ticks() / 60) % 8);
    if (! blocktype_preload(block2->block_type)) {
        render_block(block2, game->viewport);
    }
}
/* This file was generated by scramble.py. */
