/* This file was generated by scramble.py. */
#line 1 "src/title.py"
#ifndef _TITLE_
#define _TITLE_
typedef struct MenuScreenItem MenuScreenItem;
typedef struct MenuScreen MenuScreen;
#line 1
#include "common.h"
#include "main.h"
#line 4
struct MenuScreenItem {
    str text;
    MenuScreen * target;
    bool disabled;
};
struct MenuScreen {
    LandArray * items;
    int selected;
    str name;
    MenuScreen * parent;
};
#line 57
MenuScreen* menu_screen_new(void);
#line 62
MenuScreenItem* menu_screen_add(MenuScreen * self, str text);
#line 75
bool menu_is(str x);
#line 78
MenuScreenItem* menu_item_get(void);
#line 81
bool menu_item_is(str x);
#line 87
void menu_screen_back(void);
#line 98
void menu_goto(str x);
#line 112
void menu_goup(void);
#line 115
void menu_select_next(int d);
#line 125
void menu_select_position(int p);
#line 133
void menu_click(float x);
#line 211
void title_init(void);
#line 237
int get_line(float y);
#line 251
void title_com(int com);
#line 257
void title_tick(void);
#line 336
void menu_screen_draw(void);
#line 431
float align(float x, float s);
#line 434
void title_render(void);
#endif
/* This file was generated by scramble.py. */
