/* This file was generated by scramble.py. */
#line 1 "src/title.py"
#ifndef _TITLE_
#define _TITLE_
typedef struct MenuScreenItem MenuScreenItem;
typedef struct MenuScreen MenuScreen;
#line 1
#include "common.h"
#include "main.h"
#line 4
struct MenuScreenItem {
    str text;
    LandArray * alternates;
    int choice;
    MenuScreen * target;
    bool disabled;
};
struct MenuScreen {
    LandArray * items;
    int selected;
    str name;
    MenuScreen * parent;
};
#line 67
MenuScreen* menu_screen_new(void);
#line 72
MenuScreenItem* menu_screen_add(MenuScreen * self, str text);
#line 88
bool menu_is(str x);
#line 91
MenuScreenItem* menu_item_get(void);
#line 95
bool menu_item_is(str x);
#line 101
void menu_screen_back(void);
#line 112
void menu_goto(str x);
#line 126
void menu_goup(void);
#line 129
void menu_select_next(int d);
#line 139
void menu_sideways(int d);
#line 146
void menu_select_position(int p);
#line 154
void menu_click(float x);
#line 234
void title_init(void);
#line 261
int get_line(float y);
#line 275
void title_com(int com);
#line 281
void title_tick(void);
#line 371
void menu_screen_draw(void);
#line 483
float align(float x, float s);
#line 486
void title_render(void);
#endif
/* This file was generated by scramble.py. */
