/* This file was generated by scramble.py. */
#line 1 "src/title.py"
#include "title.h"
#line 15
str menu_text = "\n"
    "Play\n"
    "Reset Room\n"
    "New Game\n"
    "    -Are you sure?\n"
    "    -\n"
    "    Delete savegame!\n"
    "    Continue Playing\n"
    "Settings\n"
    "    Controls\n"
    "        Gamepad\n"
    "        Left/Right\n"
    "            -Configure H axis\n"
    "            Left\n"
    "            Right\n"
    "            Done\n"
    "        Up/Down\n"
    "            -Configure V axis\n"
    "            Up\n"
    "            Down\n"
    "            Done\n"
    "        Jump/Pull\n"
    "            -Configure buttons\n"
    "            Jump/Pull\n"
    "            Menu\n"
    "            Done\n"
    "        Back\n"
    "    Music\n"
    "    Sound\n"
    "    Back\n"
    "";
#line 47
static MenuScreen * menu;
static MenuScreen * menu_main;
static Block * block1;
static Block * block2;
static int moment;
static bool selected_blocking;
static bool finding_input;
static int finding_control;
static int finding_progress;
static void _find_control(int c);
static int _indentation(str x);
static void drawvol(int v, float x, float y);
static int volget(float mx);
static void draw_title_animation(void);
#line 57
MenuScreen* menu_screen_new(void) {
    MenuScreen * self;
#line 58
    land_alloc(self);
    self->items = land_array_new();
    return self;
}
MenuScreenItem* menu_screen_add(MenuScreen * self, str text) {
    MenuScreenItem * item;
#line 63
    land_alloc(item);
    if (land_starts_with(text, "-")) {
        item->disabled = 1;
        text++;
    }
#line 67
    if (land_equals(text, "Controls")) {
        if (global_use_touch_input) {
            text = "Touch";
        }
    }
#line 71
    item->text = text;
    land_array_add(self->items, item);
    return item;
}
bool menu_is(str x) {
    return land_equals(menu->name, x);
}
MenuScreenItem* menu_item_get(void) {
    return land_array_get_nth(menu->items, menu->selected);
}
bool menu_item_is(str x) {
    MenuScreenItem * item = menu_item_get();
    if (! item) {
        return 0;
    }
#line 85
    return land_equals(item->text, x);
}
void menu_screen_back(void) {
    if (menu_is("Settings")) {
        menu_goto("Main");
        save_info();
    }
#line 91
    else if (menu_is("New Game")) {
        main_switch_to_game();
    }
#line 93
    else if (menu_is("Controls")) {
        menu_goto("Settings");
    }
#line 95
    else if (menu_is("Main")) {
        main_switch_to_game();
    }
}
#line 98
void menu_goto(str x) {
    if (land_equals(x, "Main")) {
        menu = menu_main;
#line 100
        return ;
    }
    {
#line 102
        LandArrayIterator __iter0__ = LandArrayIterator_first(menu_main->items);
#line 102
        for (MenuScreenItem * item = LandArrayIterator_item(menu_main->items, &__iter0__); LandArrayIterator_next(menu_main->items, &__iter0__); item = LandArrayIterator_item(menu_main->items, &__iter0__)) {
            if (land_equals(item->text, x)) {
                menu = item->target;
#line 104
                return ;
            }
        }
    }
#line 106
    {
#line 106
        LandArrayIterator __iter0__ = LandArrayIterator_first(menu->items);
#line 106
        for (MenuScreenItem * item = LandArrayIterator_item(menu->items, &__iter0__); LandArrayIterator_next(menu->items, &__iter0__); item = LandArrayIterator_item(menu->items, &__iter0__)) {
            if (land_equals(item->text, x)) {
                menu = item->target;
#line 108
                return ;
            }
        }
    }
#line 110
    print("Cannot goto menu %s", x);
}
void menu_goup(void) {
    menu = menu->parent;
}
void menu_select_next(int d) {
    int n = land_array_count(menu->items);
    for (int i = 0; i < n; i += 1) {
        menu->selected += d;
        if (menu->selected == - 1) {
#line 119
            menu->selected += n;
        }
#line 120
        if (menu->selected == n) {
#line 120
            menu->selected = 0;
        }
#line 121
        MenuScreenItem * msi = land_array_get_nth(menu->items, menu->selected);
        if (msi->disabled) {
#line 122
            continue;
        }
#line 123
        break;
    }
}
#line 125
void menu_select_position(int p) {
    menu->selected = p;
}
static void _find_control(int c) {
    finding_input = 1;
    finding_control = c;
    finding_progress = 0;
}
void menu_click(float x) {
    All * a = global_a;
#line 136
    MenuScreenItem * item = menu_item_get();
    if (item) {
        if (item->target) {
            if (menu_is("Controls")) {
                menu = item->target;
                menu_select_position(1);
                menu_click(0);
#line 142
                return ;
            }
#line 145
            if (menu_is("Main")) {
                if (menu_item_is("New Game")) {
                    a->code = 0;
                    a->godmode = 0;
                }
            }
#line 149
            menu = item->target;
#line 149
            return ;
        }
    }
#line 151
    if (menu_is("Left/Right")) {
        if (menu_item_is("Left")) {
#line 152
            _find_control(ControlLeft);
        }
#line 153
        if (menu_item_is("Right")) {
#line 153
            _find_control(ControlRight);
        }
#line 154
        if (menu_item_is("Done")) {
#line 154
            menu_goup();
        }
    }
#line 155
    if (menu_is("Up/Down")) {
        if (menu_item_is("Up")) {
#line 156
            _find_control(ControlUp);
        }
#line 157
        if (menu_item_is("Down")) {
#line 157
            _find_control(ControlDown);
        }
#line 158
        if (menu_item_is("Done")) {
#line 158
            menu_goup();
        }
    }
#line 159
    if (menu_is("Jump/Pull")) {
        if (menu_item_is("Jump/Pull")) {
#line 160
            _find_control(ControlJump);
        }
#line 161
        if (menu_item_is("Menu")) {
#line 161
            _find_control(ControlMenu);
        }
#line 162
        if (menu_item_is("Done")) {
#line 162
            menu_goup();
        }
    }
#line 163
    if (menu_is("Settings")) {
        if (menu_item_is("Touch")) {
            a->dpad++;
            if (a->dpad == 6) {
                a->dpad = 0;
            }
        }
#line 168
        else if (menu_item_is("Music")) {
            a->music = volget(x);
            song_volume();
        }
#line 171
        else if (menu_item_is("Sound")) {
            a->sound = volget(x);
            sound(Render_on, 1);
        }
#line 174
        else if (menu_item_is("Back")) {
            menu_goto("Main");
            save_info();
        }
    }
#line 177
    else if (menu_is("")) {
    }
#line 178
    else if (menu_is("New Game")) {
        if (menu_item_is("Delete savegame!")) {
            // start new game
            save_new();
            main_switch_to_game();
        }
#line 183
        else if (menu_item_is("Continue Playing")) {
            main_switch_to_game();
        }
    }
#line 185
    else if (menu_is("Controls")) {
        if (menu_item_is("Back")) {
            menu_goto("Settings");
        }
    }
#line 188
    else if (menu_is("Main")) {
        if (menu_item_is("Play")) {
            if (global_can_enable_editor && volget(x) > 0) {
                a->editor_enabled = 1;
                a->editor = 1;
            }
#line 192
            else {
#line 194
                a->editor_enabled = 0;
            }
            // load saved game
            main_switch_to_game();
        }
#line 198
        else if (menu_item_is("Reset Room")) {
            // reset the current room
            save_reset_room(game->level);
            main_switch_to_game();
            if (game->player) {
                player_find_entrance(& game->player->super);
            }
        }
    }
}
#line 205
static int _indentation(str x) {
    int i = 0;
    while (x [i] == ' ') {
        i++;
    }
#line 209
    return i;
}
void title_init(void) {
    MenuScreen * menus [100];
    menus [0] = menu_main = menu_screen_new();
    menu_main->name = "Main";
    LandArray * rows = land_split_lines(menu_text);
    int prev_nested = 0;
    MenuScreenItem * prev_item = NULL;
    MenuScreen * prev_menu = NULL;
    {
#line 219
        LandArrayIterator __iter0__ = LandArrayIterator_first(rows);
#line 219
        for (str row_raw = LandArrayIterator_item(rows, &__iter0__); LandArrayIterator_next(rows, &__iter0__); row_raw = LandArrayIterator_item(rows, &__iter0__)) {
            int nested = _indentation(row_raw);
            if (nested > prev_nested) {
                menus [nested] = menu_screen_new();
                menus [nested]->name = prev_item->text;
                prev_item->target = menus [nested];
                menus [nested]->parent = prev_menu;
            }
#line 226
            prev_nested = nested;
            prev_menu = menus [nested];
            char * row = land_strdup(row_raw);
            land_strip(& row);
            if (! row [0]) {
#line 230
                continue;
            }
#line 231
            prev_item = menu_screen_add(menus [nested], row);
        }
    }
#line 233
    land_array_destroy_with_strings(rows);
#line 235
    menu = menu_main;
}
int get_line(float y) {
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
#line 243
    float by = (h - 64 * 5) / 2;
    y /= s;
    y -= by;
    y /= 64;
#line 248
    return y;
}
// 0 = main, 1 = settings
void title_com(int com) {
    if (com == 1) {
        menu_goto("Settings");
    }
#line 253
    else {
#line 255
        menu_goto("Main");
    }
}
#line 257
void title_tick(void) {
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
#line 263
    All * a = global_a;
#line 265
    if (finding_input) {
        int status = config_joystick_control(finding_control, finding_progress);
        if (status == FoundButton) {
            finding_input = 0;
        }
#line 269
        if (status == FoundAxis) {
            finding_progress++;
        }
#line 271
        if (status == FoundNothing) {
            // wait until they stop using the input
#line 272
            if (finding_progress >= 10) {
                finding_input = 0;
            }
        }
#line 274
        if (! finding_input) {
            menu_select_next(1);
            menu_click(0) /* either next control or done */;
        }
#line 276
        return ;
    }
#line 279
    if (land_key_pressed(LandKeyBack) || controls.pressed [ControlMenu]) {
        menu_screen_back();
    }
    if (selected_blocking) {
        if (! a->up && ! a->down) {
            selected_blocking = 0;
        }
    }
#line 285
    else if (a->up || a->down) {
        menu_select_next(a->up ? - 1 : 1);
        selected_blocking = 1;
    }
    for (int ti = 0; ti < 12; ti += 1) {
        bool click = 0;
        int i = 0;
        int i2 = 0;
        float x = 0;
        if (ti < 11) {
            if (land_touch_down(ti) && land_touch_delta(ti)) {
                click = 1;
            }
#line 297
            i2 = get_line(land_touch_y(ti));
            i = i2;
            if (i > 0) {
#line 299
                i--;
            }
#line 300
            x = land_touch_x(ti);
        }
#line 300
        else {
#line 302
            if (controls.pressed [ControlJump]) {
                i = menu->selected;
                click = 1;
            }
        }
#line 306
        if (click) {
            if (i2 == 1) {
                if (menu_is("New Game")) {
                    a->code++;
                    if (a->code == 7) {
                        sound(Render_glass, 1);
                        a->godmode = 1;
                    }
                }
            }
#line 312
            else {
#line 314
                menu_select_position(i);
                menu_click(x);
            }
        }
    }
}
#line 317
static int volx = 0;
static void drawvol(int v, float x, float y) {
    LandColor c = land_color_get();
    y += 16;
    float s = 48;
    for (int i = 0; i < 7; i += 1) {
        float ix = x + i * s;
        float iy = y;
        land_color(1, 1, 1, 1);
        if (i <= v) {
            if (v == 0) {
                land_color(0, 0, 0, 1);
            }
#line 329
            land_filled_rectangle(ix, iy, ix + s * 0.8, iy + s);
        }
#line 329
        else {
#line 331
            float cx = ix + s * 0.4;
            float cy = iy + s * 0.5;
            land_filled_circle(cx - 4, cy - 4, cx + 4, cy + 4);
        }
    }
#line 334
    land_color_set(c);
}
void menu_screen_draw(void) {
    All * a = global_a;
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
    land_font_set(a->big);
    float th = land_line_height();
    float yw = land_text_get_width("Yellow ");
    land_color(.9, .9, 0.7, 1);
    float tx = (960 - land_text_get_width("Yellow and Dangerous")) / 2;
#line 348
    int it = 0;
    {
#line 349
        LandArrayIterator __iter0__ = LandArrayIterator_first(menu->items);
#line 349
        for (MenuScreenItem * item = LandArrayIterator_item(menu->items, &__iter0__); LandArrayIterator_next(menu->items, &__iter0__); item = LandArrayIterator_item(menu->items, &__iter0__)) {
            int it2 = it;
            if (it2 > 0) {
                it2++;
            }
#line 353
            float y = (h - 64 * 5) / 2 + it2 * 64 + (32 - th) / 2;
            float x = tx;
            bool draw = 1;
            land_text_pos(x + yw, y);
            land_color(0.5, 0, 0, 1);
            if (it == menu->selected) {
                land_color(0.9, 0.1, 0, 1);
                if (finding_input) {
                    if ((land_get_ticks() / 5) % 2 == 0) {
                        land_color(1, 1, 1, 1);
                    }
                }
            }
#line 362
            else {
#line 364
                land_color(0.5, 0, 0, 1);
            }
            if (menu_is("Settings")) {
                if (it == 0) {
                    if (global_use_touch_input) {
                        if (a->dpad == 0) {
#line 369
                            land_print("DPad left");
                        }
#line 370
                        if (a->dpad == 1) {
#line 370
                            land_print("DPad right");
                        }
#line 371
                        if (a->dpad == 2) {
#line 371
                            land_print("DPad left big");
                        }
#line 372
                        if (a->dpad == 3) {
#line 372
                            land_print("DPad right big");
                        }
#line 373
                        if (a->dpad == 4) {
#line 373
                            land_print("double click swipe");
                        }
#line 374
                        if (a->dpad == 5) {
#line 374
                            land_print("two finger swipe");
                        }
#line 375
                        draw = 0;
                    }
                }
#line 376
                else if (it == 1) {
                    drawvol(a->music, volx, y);
                }
#line 378
                else if (it == 2) {
                    drawvol(a->sound, volx, y);
                }
            }
#line 380
            else if (menu_is("New Game")) {
                if (it == 0) {
                    land_color(1, 0.75, 0.75, 1);
                }
#line 383
                else if (it == 2) {
                    if (it == menu->selected) {
                        land_color(1, 0.4, 0.4, 1);
                    }
                }
#line 386
                else if (it == 3) {
                    if (it == menu->selected) {
                        land_color(0, 0.5, 0, 1);
                    }
                }
            }
#line 390
            if (draw) {
                land_print(item->text);
            }
            if (menu_is("Main")) {
                if (it == 0) {
                    if (global_can_enable_editor) {
                        land_text_pos(volx + 48, y);
                        land_print("Edit");
                    }
                }
            }
#line 399
            int control = ControlNone;
            if (menu_is("Left/Right")) {
                if (it == 1) {
#line 401
                    control = ControlLeft;
                }
#line 402
                if (it == 2) {
#line 402
                    control = ControlRight;
                }
            }
#line 403
            if (menu_is("Up/Down")) {
                if (it == 1) {
#line 404
                    control = ControlUp;
                }
#line 405
                if (it == 2) {
#line 405
                    control = ControlDown;
                }
            }
#line 406
            if (menu_is("Jump/Pull")) {
                if (it == 1) {
#line 407
                    control = ControlJump;
                }
#line 408
                if (it == 2) {
#line 408
                    control = ControlMenu;
                }
            }
#line 409
            if (menu_is("Controls")) {
                if (it == 1) {
#line 410
                    control = ControlLeft;
                }
#line 411
                if (it == 2) {
#line 411
                    control = ControlUp;
                }
#line 412
                if (it == 3) {
#line 412
                    control = ControlJump;
                }
            }
#line 414
            if (control) {
                land_text_pos(volx + 68, y);
                land_color(0, 0, 0, 0.33);
                land_print(control_name(control));
            }
            it++;
        }
    }
}
#line 421
static int volget(float mx) {
    float w = land_display_width();
    double s = w / 960;
    float sx = 48;
    mx /= s;
    int i = (mx - volx) / sx;
    if (i < 0) {
#line 427
        i = 0;
    }
#line 428
    if (i > 6) {
#line 428
        i = 6;
    }
#line 429
    return i;
}
float align(float x, float s) {
    return floor(x * s) / s;
}
void title_render(void) {
    All * a = global_a;
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
    land_clear(1, 1, 1, 1);
#line 442
    land_reset_transform();
    land_scale(s, s);
#line 445
    land_font_set(a->big);
    float th = land_line_height();
    float yw = land_text_get_width("Yellow ");
#line 449
    land_color(.9, .9, 0.7, 1);
    float tx = (960 - land_text_get_width("Yellow and Dangerous")) / 2;
    land_filled_rectangle(tx + yw, 0, 960, h);
#line 453
    if (menu_is("Settings") && global_use_touch_input) {
        land_font_set(a->medium);
        land_color(0.5, 0, 0, 1);
        float nh = land_line_height();
        float y = (h - 64 * 5) / 2 + (32 - th) / 2;
        float x = tx;
        land_text_pos(x + yw, y - nh * 2);
        if (a->dpad == 5) {
            land_print("Jump: touch second finger");
            land_print("Pull/Lift: two finger swipe");
        }
#line 463
        else if (a->dpad == 4) {
            land_print("Jump: Move then double tap");
            land_print("Pull/Lift: Double tap then move");
        }
#line 465
        else {
#line 467
            land_print("Jump: Hold move then jump");
            land_print("Pull/Lift: Hold jump then move");
        }
#line 469
        land_font_set(a->big);
    }
    volx = tx + yw + 6 * 32;
#line 473
    if (1) {
        int i = 1;
        float y = (h - 64 * 5) / 2 + i * 64 + (32 - th) / 2;
        float x = tx;
        land_color(1, 0.9, 0, 1);
        land_text_pos(x, y);
        land_write("Yellow ");
        land_color(1, 1, 1, 1);
        if ((land_get_ticks() / 60) % 14 >= 7) {
            if (land_get_ticks() % 8 >= 4) {
                land_color(1, 1, 0, 1);
            }
        }
#line 484
        land_print("and Dangerous");
    }
    menu_screen_draw();
#line 488
    land_font_set(a->font);
    land_color(0, 0, 0, 1);
#line 491
    if (! block1) {
        block1 = block_new(game->blocks, 120, 0, 720, Render_Gremlin);
    }
#line 493
    if (! block2) {
        block2 = block_new(game->blocks, - 660, 0, - 60, Render_Allefant);
    }
    moment++;
    if (moment > 4) {
        // wait a moment so Android gets a moment to recover and
        // won't crash :P
        draw_title_animation();
    }
    a->tint.a = 0;
#line 504
    land_font_set(a->font);
    land_text_pos(w / s, h - land_line_height() * 6);
    int t = a->time / 60;
    int f = 0;
    for (int i = 0; i < 8; i += 1) {
        if (game->flower [i]) {
            f++;
        }
    }
#line 511
    int tt = 0;
    for (int i = 0; i < 8; i += 1) {
        if (game->test_tube [i]) {
            tt++;
        }
    }
#line 515
    land_print_right("Flowers picked: %d/7", f);
    land_print_right("Test tubes: %d/7", tt);
    land_print_right("Car keys found: %s", game->key ? "yes" : "no");
    land_print_right("Died %d time%s.", game->deaths, game->deaths != 1 ? "s" : "");
#line 520
    land_print_right("Playtime on this savegame: %02d:%02d:%02d", t / 3600, (t / 60) % 60, t % 60);
    land_print_right("Version %s", VERSION);
}
static void draw_title_animation(void) {
    All * a = global_a;
    float speed = 60 * 7 / 2.0;
    for (int i = 0; i < 7; i += 1) {
        float ang = (land_get_ticks() + i * speed / 7) * 2 * pi / speed;
        block1->y = 60 * fabs(sin(ang * 3.5));
        block1->x = 0 + cos(ang) * 120;
        block1->z = 600 + sin(ang) * 120;
        block1->frame = ((land_get_ticks() / 30 + i) % 4) * 4;
        if (((land_get_ticks() / 60) % 14 >= 7) && i == 0) {
            a->tint = land_color_hsv((land_get_ticks() * 4) % 360, .25, 1);
            a->tint.a = 0.5;
            a->tint.r *= a->tint.a;
            a->tint.g *= a->tint.a;
            a->tint.b *= a->tint.a;
        }
#line 537
        else {
#line 539
            a->tint = land_color_premul(1, 1, 1, .2);
        }
#line 540
        if (! blocktype_preload(block1->block_type)) {
            render_block(block1, game->viewport);
        }
    }
#line 543
    a->tint = land_color_premul(1, 1, 1, .2);
#line 545
    block2->frame = 8 + ((16 * land_get_ticks() / 60) % 8);
    if (! blocktype_preload(block2->block_type)) {
        render_block(block2, game->viewport);
    }
}
/* This file was generated by scramble.py. */
