/* This file was generated by scramble.py. */
#line 1 "src/title.py"
#ifndef _TITLE_
#define _TITLE_
typedef struct MenuScreenItem MenuScreenItem;
typedef struct MenuScreen MenuScreen;
#line 1
#include "common.h"
#include "main.h"
#line 4
struct MenuScreenItem {
    str text;
    LandArray * alternates;
    int choice;
    MenuScreen * target;
    bool disabled;
};
struct MenuScreen {
    LandArray * items;
    int selected;
    str name;
    MenuScreen * parent;
};
#line 65
MenuScreen* menu_screen_new(void);
#line 70
MenuScreenItem* menu_screen_add(MenuScreen * self, str text);
#line 86
bool menu_is(str x);
#line 89
MenuScreenItem* menu_item_get(void);
#line 92
bool menu_item_is(str x);
#line 98
void menu_screen_back(void);
#line 109
void menu_goto(str x);
#line 123
void menu_goup(void);
#line 126
void menu_select_next(int d);
#line 136
void menu_sideways(int d);
#line 143
void menu_select_position(int p);
#line 151
void menu_click(float x);
#line 231
void title_init(void);
#line 258
int get_line(float y);
#line 272
void title_com(int com);
#line 278
void title_tick(void);
#line 360
void menu_screen_draw(void);
#line 472
float align(float x, float s);
#line 475
void title_render(void);
#endif
/* This file was generated by scramble.py. */
