/* This file was generated by scramble.py. */
#line 1 "src/title.py"
#include "title.h"
static void drawvol(int v, float x, float y);
static int volget(float mx);
#line 4
static bool settings;
static bool restart;
static Block * block1;
static Block * block2;
static int moment;
#line 10
int get_line(float y) {
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
#line 16
    float by = (h - 64 * 5) / 2;
    y /= s;
    y -= by;
    y /= 64;
#line 21
    return y;
}
void title_com(int com) {
    if (com == 1) {
        settings = 1;
    }
}
#line 27
void title_tick(void) {
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
#line 33
    All * a = global_a;
#line 35
    if (land_key_pressed(LandKeyEnter)) {
        main_switch_to_game();
    }
    if (land_key_pressed(LandKeyBack)) {
        if (settings) {
            settings = 0;
            save_info();
        }
#line 42
        else if (restart) {
            main_switch_to_game();
            restart = 0;
        }
#line 44
        else {
#line 46
            load_info();
            main_switch_to_game();
        }
    }
#line 49
    for (int ti = 0; ti < 11; ti += 1) {
        if (land_touch_down(ti) && land_touch_delta(ti)) {
            int i = get_line(land_touch_y(ti));
            if (settings) {
                if (i == 0) {
                    a->dpad++;
                    if (a->dpad == 6) {
                        a->dpad = 0;
                    }
                }
#line 57
                else if (i == 2) {
                    a->music = volget(land_touch_x(ti));
                    song_volume();
                }
#line 60
                else if (i == 3) {
                    a->sound = volget(land_touch_x(ti));
                    sound(Render_on, 1);
                }
#line 63
                else if (i == 4) {
                    settings = 0;
                    save_info();
                }
            }
#line 66
            else if (restart) {
                if (i == 1) {
                    a->code++;
                    if (a->code == 7) {
                        sound(Render_glass, 1);
                        a->godmode = 1;
                    }
                }
#line 72
                else if (i == 3) {
                    // start new game
                    save_new();
                    main_switch_to_game();
                    restart = 0;
                }
#line 77
                else if (i == 4) {
                    main_switch_to_game();
                    restart = 0;
                }
            }
#line 79
            else {
#line 81
                if (i == 2) {
                    // reset the current room
                    load_info();
                    save_reset_room(game->level);
                    main_switch_to_game();
                    if (game->player) {
                        player_find_entrance(& game->player->super);
                    }
                }
#line 88
                if (i == 3) {
                    a->code = 0;
                    a->godmode = 0;
                    restart = 1;
                }
#line 92
                if (i == 0) {
                    if (global_can_enable_editor && volget(land_touch_x(ti)) > 0) {
                        a->editor_enabled = 1;
                        a->editor = 1;
                    }
#line 95
                    else {
#line 97
                        a->editor_enabled = 0;
                    }
                    // load saved game
                    load_info();
                    main_switch_to_game();
                }
#line 102
                if (i == 4) {
                    load_info();
                    settings = 1;
                }
            }
        }
    }
}
#line 106
static int volx = 0;
static void drawvol(int v, float x, float y) {
    y += 16;
    float s = 48;
    for (int i = 0; i < 7; i += 1) {
        float ix = x + i * s;
        float iy = y;
        land_color(1, 1, 1, 1);
        if (i <= v) {
            if (v == 0) {
                land_color(0, 0, 0, 1);
            }
#line 117
            land_filled_rectangle(ix, iy, ix + s * 0.8, iy + s);
        }
#line 117
        else {
#line 119
            float cx = ix + s * 0.4;
            float cy = iy + s * 0.5;
            land_filled_circle(cx - 4, cy - 4, cx + 4, cy + 4);
        }
    }
}
#line 123
static int volget(float mx) {
    float w = land_display_width();
    double s = w / 960;
    float sx = 48;
    mx /= s;
    int i = (mx - volx) / sx;
    if (i < 0) {
#line 129
        i = 0;
    }
#line 130
    if (i > 6) {
#line 130
        i = 6;
    }
#line 131
    return i;
}
float align(float x, float s) {
    return floor(x * s) / s;
}
void title_render(void) {
    All * a = global_a;
    float w = land_display_width();
    float h = land_display_height();
    double s = w / 960;
    h /= s;
    land_clear(1, 1, 1, 1);
    land_reset_transform();
    land_scale(s, s);
#line 146
    land_font_set(a->big);
    float th = land_line_height();
    float yw = land_text_get_width("Yellow ");
#line 150
    land_color(.9, .9, 0.7, 1);
    float tx = (960 - land_text_get_width("Yellow and Dangerous")) / 2;
    land_filled_rectangle(tx + yw, 0, 960, h);
#line 154
    if (settings) {
        land_font_set(a->medium);
        land_color(0.5, 0, 0, 1);
        float nh = land_line_height();
        float y = (h - 64 * 5) / 2 + (32 - th) / 2;
        float x = tx;
        land_text_pos(x + yw, y - nh * 2);
        if (a->dpad == 5) {
            land_print("Jump: touch second finger");
            land_print("Pull/Lift: two finger swipe");
        }
#line 164
        else if (a->dpad == 4) {
            land_print("Jump: Move then double tap");
            land_print("Pull/Lift: Double tap then move");
        }
#line 166
        else {
#line 168
            land_print("Jump: Hold move then jump");
            land_print("Pull/Lift: Hold jump then move");
        }
#line 170
        land_font_set(a->big);
    }
    volx = tx + yw + 6 * 32;
#line 174
    for (int i = 0; i < 5; i += 1) {
        float y = (h - 64 * 5) / 2 + i * 64 + (32 - th) / 2;
        float x = tx;
        land_text_pos(x + yw, y);
        land_color(0.5, 0, 0, 1);
        if (i == 1) {
            land_color(1, 0.9, 0, 1);
            land_text_pos(x, y);
            land_write("Yellow ");
            land_color(1, 1, 1, 1);
            if ((land_get_ticks() / 60) % 14 >= 7) {
                if (land_get_ticks() % 8 >= 4) {
                    land_color(1, 1, 0, 1);
                }
            }
#line 187
            land_print("and Dangerous");
        }
#line 188
        if (settings) {
            if (i == 0) {
                if (a->dpad == 0) {
#line 190
                    land_print("DPad left");
                }
#line 191
                if (a->dpad == 1) {
#line 191
                    land_print("DPad right");
                }
#line 192
                if (a->dpad == 2) {
#line 192
                    land_print("DPad left big");
                }
#line 193
                if (a->dpad == 3) {
#line 193
                    land_print("DPad right big");
                }
#line 194
                if (a->dpad == 4) {
#line 194
                    land_print("double click swipe");
                }
#line 195
                if (a->dpad == 5) {
#line 195
                    land_print("two finger swipe");
                }
            }
#line 196
            else if (i == 2) {
                land_print("Music");
                drawvol(a->music, volx, y);
            }
#line 199
            else if (i == 3) {
                land_print("Sound");
                drawvol(a->sound, volx, y);
            }
#line 202
            else if (i == 4) {
                land_print("Back");
            }
        }
#line 204
        else if (restart) {
            if (i == 0) {
                land_color(1, 0.75, 0.75, 1);
                land_print("Are you sure?");
            }
#line 208
            else if (i == 3) {
                land_color(1, 0, 0, 1);
                land_print("Delete savegame!");
            }
#line 211
            else if (i == 4) {
                land_color(0, 0.5, 0, 1);
                land_print("Continue playing");
            }
        }
#line 213
        else {
#line 215
            if (i == 0) {
                land_print("Play");
                if (global_can_enable_editor) {
                    land_text_pos(volx + 48, y);
                    land_print("Edit");
                }
            }
#line 220
            else if (i == 2) {
                land_print("Reset room");
            }
#line 222
            else if (i == 3) {
                land_print("New game");
            }
#line 224
            else if (i == 4) {
                land_print("Settings");
            }
        }
    }
#line 227
    land_font_set(a->font);
    land_color(0, 0, 0, 1);
#line 230
    if (! block1) {
        block1 = block_new(game->blocks, 120, 0, 720, Render_Gremlin);
    }
#line 232
    if (! block2) {
        block2 = block_new(game->blocks, - 660, 0, - 60, Render_Allefant);
    }
    moment++;
    if (moment > 4) {
        // wait a moment so Android gets a moment to recover and
        // won't crash :P
        float speed = 60 * 7 / 2.0;
        for (int i = 0; i < 7; i += 1) {
            float ang = (land_get_ticks() + i * speed / 7) * 2 * pi / speed;
            block1->y = 60 * fabs(sin(ang * 3.5));
            block1->x = 0 + cos(ang) * 120;
            block1->z = 600 + sin(ang) * 120;
            block1->frame = ((land_get_ticks() / 30 + i) % 4) * 4;
            if (((land_get_ticks() / 60) % 14 >= 7) && i == 0) {
                a->tint = land_color_hsv((land_get_ticks() * 4) % 360, .25, 1);
                a->tint.a = 0.5;
                a->tint.r *= a->tint.a;
                a->tint.g *= a->tint.a;
                a->tint.b *= a->tint.a;
            }
#line 251
            else {
#line 253
                a->tint = land_color_premul(1, 1, 1, .2);
            }
#line 254
            if (! blocktype_preload(block1->block_type)) {
                render_block(block1, game->viewport);
            }
        }
#line 257
        a->tint = land_color_premul(1, 1, 1, .2);
#line 259
        block2->frame = 8 + ((16 * land_get_ticks() / 60) % 8);
        if (! blocktype_preload(block2->block_type)) {
            render_block(block2, game->viewport);
        }
    }
#line 263
    a->tint.a = 0;
#line 265
    land_font_set(a->font);
    land_text_pos(w / s, h - land_line_height() * 5);
    int t = a->time / 60;
    int f = 0;
    for (int i = 0; i < 8; i += 1) {
        if (game->flower [i]) {
            f++;
        }
    }
#line 272
    land_print_right("Flowers picked: %d/7", f);
    land_print_right("Car keys found: %s", game->key ? "yes" : "no");
    land_print_right("Died %d time%s.", game->deaths, game->deaths != 1 ? "s" : "");
#line 276
    land_print_right("Playtime on this savegame: %02d:%02d:%02d", t / 3600, (t / 60) % 60, t % 60);
    land_print_right("Version %s", VERSION);
}
/* This file was generated by scramble.py. */
