/* This file was generated by scramble.py. */
#line 1 "src/vent.py"
#ifndef _VENT_
#define _VENT_
typedef struct Vent Vent;
#line 1
#include "common.h"
#include "block.h"
#line 2
#include "render.h"
#line 4
struct Vent {
    Block super;
    bool on;
    int offset;
    float accum;
};
Block* vent_allocate(void);
#line 15
void vent_tick(Block * super);
#endif
/* This file was generated by scramble.py. */
